# Generate resource XMLs from extracted resources library
# Creates separate files: dimens.xml, colors.xml, strings.xml

param(
    [string]$InputFile = "temp\resources_library.json",
    [string]$OutputDir = "temp\generated_resources",
    [switch]$GroupByLayout = $false,
    [switch]$SortByValue = $false,
    [string[]]$Types = @('dimension', 'color_hex', 'string_literal')
)

$ErrorActionPreference = "Stop"

Write-Host "=== Universal Resource XML Generation Script ===" -ForegroundColor Cyan
Write-Host "Input: $InputFile" -ForegroundColor Gray
Write-Host "Output: $OutputDir" -ForegroundColor Gray
Write-Host "Types: $($Types -join ', ')" -ForegroundColor Gray
Write-Host ""

# Load JSON library
$inputPath = Join-Path $PSScriptRoot "..\..\$InputFile"

if (-not (Test-Path $inputPath)) {
    Write-Host "[!] Input file not found: $inputPath" -ForegroundColor Red
    Write-Host "[!] Run 1-extract-dimensions.ps1 first" -ForegroundColor Yellow
    exit 1
}

Write-Host "[*] Loading resources library..." -ForegroundColor Cyan
$library = Get-Content -Path $inputPath -Raw -Encoding UTF8 | ConvertFrom-Json -AsHashtable

if ($library.Count -eq 0) {
    Write-Host "[!] No resources found in library" -ForegroundColor Red
    exit 1
}

Write-Host "  [✓] Loaded $($library.Count) unique resources" -ForegroundColor Green
Write-Host ""

# Build XML structure
$xmlBuilder = [System.Text.StringBuilder]::new()
[void]$xmlBuilder.AppendLine('<?xml version="1.0" encoding="utf-8"?>')
[void]$xmlBuilder.AppendLine('<!-- Auto-generated by layout-dimen-migration scripts -->')
[void]$xmlBuilder.AppendLine('<!-- DO NOT EDIT MANUALLY - Regenerate using 2-generate-dimens.ps1 -->')
[void]$xmlBuilder.AppendLine('<resources>')

# Sort dimensions
Write-Host "[*] Organizing dimensions..." -ForegroundColor Cyan

$dimensions = $library.GetEnumerator() | ForEach-Object { 
    [PSCustomObject]@{
        Key  = $_.Key
        Data = $_.Value
    }
}

if ($GroupByLayout) {
    $dimensions = $dimensions | Sort-Object { $_.Data.layout }, { $_.Data.attribute }, { $_.Key }
    Write-Host "  [✓] Grouped by layout" -ForegroundColor Green
}
elseif ($SortByValue) {
    $dimensions = $dimensions | Sort-Object { 
        # Extract numeric value for sorting
        if ($_.Data.value -match '(\d+(?:\.\d+)?)(dp|sp)') {
            [float]$matches[1]
        }
        else {
            0
        }
    }, { $_.Key }
    Write-Host "  [✓] Sorted by value" -ForegroundColor Green
}
else {
    $dimensions = $dimensions | Sort-Object { $_.Key }
    Write-Host "  [✓] Sorted alphabetically" -ForegroundColor Green
}

# Generate XML entries
$currentLayout = $null
$statsCount = 0

foreach ($dim in $dimensions) {
    $data = $dim.Data
    
    # Add layout separator comment
    if ($GroupByLayout -and $data.layout -ne $currentLayout) {
        [void]$xmlBuilder.AppendLine()
        [void]$xmlBuilder.AppendLine("    <!-- ================================ -->")
        [void]$xmlBuilder.AppendLine("    <!-- Layout: $($data.layout) -->")
        [void]$xmlBuilder.AppendLine("    <!-- ================================ -->")
        $currentLayout = $data.layout
    }
    
    # Add dimension entry
    $dimenName = $dim.Key
    $value = $data.value
    $comment = ""
    
    # Add usage count if available
    if ($data.usages -and $data.usages.Count -gt 1) {
        $comment = " <!-- Used $($data.usages.Count) times -->"
    }
    
    [void]$xmlBuilder.AppendLine("    <dimen name=`"$dimenName`">$value</dimen>$comment")
    $statsCount++
}

[void]$xmlBuilder.AppendLine('</resources>')

# Save XML file
$outputPath = Join-Path $PSScriptRoot "..\..\$OutputFile"
$outputDir = Split-Path -Parent $outputPath

if (-not (Test-Path $outputDir)) {
    New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
}

$xmlBuilder.ToString() | Out-File -FilePath $outputPath -Encoding UTF8

Write-Host ""
Write-Host "=== Generation Complete ===" -ForegroundColor Cyan
Write-Host "  Dimensions written: $statsCount" -ForegroundColor Green
Write-Host "  Output file: $outputPath" -ForegroundColor Green
Write-Host "  Size: $([math]::Round((Get-Item $outputPath).Length / 1KB, 2)) KB" -ForegroundColor Green
Write-Host ""

# Generate statistics
$stats = @{
    byAttribute = @{}
    byLayout    = @{}
    byValue     = @{}
}

foreach ($dim in $dimensions) {
    $data = $dim.Data
    
    # Count by attribute
    if (-not $stats.byAttribute.ContainsKey($data.attribute)) {
        $stats.byAttribute[$data.attribute] = 0
    }
    $stats.byAttribute[$data.attribute]++
    
    # Count by layout
    if (-not $stats.byLayout.ContainsKey($data.layout)) {
        $stats.byLayout[$data.layout] = 0
    }
    $stats.byLayout[$data.layout]++
    
    # Count by value
    if (-not $stats.byValue.ContainsKey($data.value)) {
        $stats.byValue[$data.value] = 0
    }
    $stats.byValue[$data.value]++
}

# Display top statistics
Write-Host "=== Statistics ===" -ForegroundColor Cyan
Write-Host ""

Write-Host "Top 10 Attributes:" -ForegroundColor Yellow
$stats.byAttribute.GetEnumerator() | 
Sort-Object Value -Descending | 
Select-Object -First 10 | 
ForEach-Object { Write-Host "  $($_.Key): $($_.Value)" -ForegroundColor Gray }

Write-Host ""
Write-Host "Top 10 Most Used Values:" -ForegroundColor Yellow
$stats.byValue.GetEnumerator() | 
Sort-Object Value -Descending | 
Select-Object -First 10 | 
ForEach-Object { Write-Host "  $($_.Key): used $($_.Value) times" -ForegroundColor Gray }

Write-Host ""
Write-Host "[✓] Next step: Review $outputPath and consolidate duplicates" -ForegroundColor Green
Write-Host "[✓] Then run: 3-replace-with-dimens.ps1" -ForegroundColor Green
