<#
.SYNOPSIS
    Refresh verified public APK fallbacks for the product's edition cards.
.PARAMETER ReleasesFile
    Optional saved GitHub releases response for offline validation.
.PARAMETER Root
    Repository root, defaulting to this script's parent tree.
.NOTES
    Manual tool: run by hand after a GitHub release publishes new APK assets, to refresh _data/downloads.json.
    Only published APK assets qualify; local builds and Play AABs are never advertised as APKs.
    Exit codes:
      0 - verified manifest written.
      1 - release retrieval or validation failed; the previous manifest is untouched.
#>
[CmdletBinding()]
param([string]$ReleasesFile, [string]$Root = (Split-Path -Parent (Split-Path -Parent $PSScriptRoot)))
$ErrorActionPreference = 'Stop'
try {
    $repo = 'SerZhyAle/FastMediaSorter_mob_v2'
    $truncated = $false
    if ($ReleasesFile) { $releases = @(Get-Content -LiteralPath $ReleasesFile -Raw | ConvertFrom-Json) }
    else {
        $releases = @()
        for ($page = 1; $page -le 3; $page++) {
            $part = @(Invoke-RestMethod "https://api.github.com/repos/$repo/releases?per_page=100&page=$page" -TimeoutSec 30)
            $releases += $part
            if ($part.Count -lt 100) { break }
            if ($page -eq 3) { $truncated = $true }
        }
    }
    $editions = [ordered]@{}
    foreach ($edition in 'noLegal', 'vr', 'wear', 'watchface') {
        $entry = $null
        foreach ($release in @($releases | Where-Object { -not $_.draft } | Sort-Object published_at -Descending)) {
            $asset = @($release.assets | Where-Object {
                $_.name -match "^FastMediaSorter-$edition-.+\.apk$" -and
                $_.browser_download_url.StartsWith("https://github.com/$repo/releases/download/", [StringComparison]::Ordinal)
            } | Select-Object -First 1)
            if (-not $asset.Count) { continue }
            $entry = [ordered]@{ url = $asset[0].browser_download_url; version = $release.tag_name; prerelease = [bool]$release.prerelease }
            break
        }
        $editions[$edition] = $entry
    }
    if ($truncated -and @($editions.Values | Where-Object { $null -eq $_ }).Count) { throw 'History limit reached with unresolved editions; keep the previous manifest.' }
    $manifest = [ordered]@{ '_comment' = 'GENERATED by scripts/site/update-download-manifest.ps1; latest published APK per edition, including marked test builds.'; editions = $editions }
    $json = ($manifest | ConvertTo-Json -Depth 6) -replace "`r`n", "`n"
    [IO.File]::WriteAllText((Join-Path $Root '_data/downloads.json'), $json + "`n", [Text.UTF8Encoding]::new($false))
    Write-Host 'update-download-manifest: PASS'
    exit 0
} catch { Write-Host "update-download-manifest: FAIL - $_"; exit 1 }
