"""Generate the splash brand drawable (arrows + wordmark + slogan) for every locale.

The Android splash icon slot is a 288-unit asset whose visible area is a 192-unit
circle, so everything drawn must sit inside that circle. The slogan's point size is
therefore chosen per locale by measuring the real outline bounds: cap height alone is
not enough, because descenders reach below the baseline and the circle narrows fast
towards the bottom of the asset.

Driven by generate-splash-brand.ps1 - do not call directly except when debugging.
"""
import argparse
import os
import re
import sys
import xml.etree.ElementTree as ET

from fontTools.ttLib import TTFont
from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen

VIEWPORT = 288.0
CIRCLE_R = 96.0
CENTRE = VIEWPORT / 2.0
FIT_MARGIN = 0.96

SLOGAN_FONT = os.path.join(os.environ.get("WINDIR", r"C:\Windows"), "Fonts", "georgiai.ttf")
SLOGAN_BASELINE = 207.0
SLOGAN_SIZES = [18, 17, 16, 15, 14, 13, 12]

ARROWS_PATH = ("M10,9h4L14,6h3l-5,-5 -5,5h3v3zM9,10L6,10L6,7l-5,5 5,5v-3h3v-4z"
               "M23,12l-5,-5v3h-3v4h3v3l5,-5zM14,15h-4v3L7,18l5,5 5,-5h-3v-3z")
ARROWS_SCALE = 3.8
ARROWS_TX = 98.4
ARROWS_TY = 58.0
ARROWS_PIVOT_X = 144.0
ARROWS_PIVOT_Y = ARROWS_TY + 12.0 * ARROWS_SCALE
WORDMARK_TRANSLATE_Y = -14.0

# Arrows-only composition (the watch). Measured on a Galaxy Watch 7 (480x480 at 320 dpi): the
# phone's wordmark rendered 10 px tall and the slogan 12 px, about 5-7 dp against Wear OS's 12 sp
# floor, so both are dropped rather than shipped unreadable. With the text gone the arrows are
# re-centred and grown to the largest square that still fits the 192-unit mask circle.
ARROWS_ONLY_SCALE = 5.4
ARROWS_ONLY_T = (VIEWPORT - 24.0 * ARROWS_ONLY_SCALE) / 2.0

STRING_KEY = "splash_slogan"


def render_line(font_path, text, size, baseline_y):
    """Render one centred line; return (path data, bounds, width) or None."""
    font = TTFont(font_path)
    upm = font["head"].unitsPerEm
    cmap = font.getBestCmap()
    glyphs = font.getGlyphSet()
    hmtx = font["hmtx"]
    scale = size / upm

    width = 0.0
    for ch in text:
        gname = cmap.get(ord(ch))
        if gname is None:
            print(f"  no glyph for {ch!r} in {os.path.basename(font_path)}", file=sys.stderr)
            continue
        width += hmtx[gname][0] * scale

    pen_x = CENTRE - width / 2.0
    parts = []
    box = [float("inf"), float("inf"), float("-inf"), float("-inf")]
    for ch in text:
        gname = cmap.get(ord(ch))
        if gname is None:
            continue
        # y is negated: font units grow upward, drawable coordinates grow downward
        transform = (scale, 0, 0, -scale, pen_x, baseline_y)
        svg = SVGPathPen(glyphs, ntos=lambda v: f"{v:.1f}")
        glyphs[gname].draw(TransformPen(svg, transform))
        drawn = svg.getCommands()
        if drawn.strip():
            parts.append(drawn)
            bounds = BoundsPen(glyphs)
            glyphs[gname].draw(TransformPen(bounds, transform))
            if bounds.bounds:
                x0, y0, x1, y1 = bounds.bounds
                box = [min(box[0], x0), min(box[1], y0), max(box[2], x1), max(box[3], y1)]
        pen_x += hmtx[gname][0] * scale

    if not parts:
        return None
    return " ".join(parts), tuple(box), width


def inside_circle(bounds):
    """A rectangle lies inside a circle exactly when all four of its corners do."""
    x0, y0, x1, y1 = bounds
    limit = CIRCLE_R * FIT_MARGIN
    for x in (x0, x1):
        for y in (y0, y1):
            if ((x - CENTRE) ** 2 + (y - CENTRE) ** 2) ** 0.5 > limit:
                return False
    return True


def fit_line(text, baseline_y=SLOGAN_BASELINE):
    """Largest candidate size whose outline fits the mask circle, or (None, None, w)."""
    widest = 0.0
    for size in SLOGAN_SIZES:
        rendered = render_line(SLOGAN_FONT, text, size, baseline_y)
        if rendered is None:
            return None, None, 0.0
        path_d, bounds, width = rendered
        widest = width
        if inside_circle(bounds):
            return size, path_d, width
    return None, None, widest


def read_slogan(strings_path):
    try:
        root = ET.parse(strings_path).getroot()
    except ET.ParseError as exc:
        print(f"  cannot parse {strings_path}: {exc}", file=sys.stderr)
        return None
    for node in root.findall("string"):
        if node.get("name") == STRING_KEY:
            text = "".join(node.itertext()).strip()
            return text.strip('"').replace("\\'", "'")
    return None


def build_arrows_only_xml():
    return f"""<?xml version="1.0" encoding="utf-8"?>
<!--
    GENERATED by scripts/utils/generate-splash-brand.ps1 (S1706) - do not hand-edit.
    Arrows-only splash centre for the watch: at watch size the wordmark and the slogan fall
    below the legible floor, so the logo carries the splash alone and grows to fill the mask.
-->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt"
    android:width="288dp"
    android:height="288dp"
    android:viewportWidth="288"
    android:viewportHeight="288">
    <group android:name="splash">
        <group
            android:name="arrows"
            android:pivotX="{CENTRE}"
            android:pivotY="{CENTRE}">
            <group
                android:scaleX="{ARROWS_ONLY_SCALE}"
                android:scaleY="{ARROWS_ONLY_SCALE}"
                android:translateX="{ARROWS_ONLY_T}"
                android:translateY="{ARROWS_ONLY_T}">
                <path
                    android:name="arrowsPath"
                    android:fillAlpha="1"
                    android:pathData="{ARROWS_PATH}">
                    <!-- The gradient runs in the path's own 24-unit space, not the 288
                         viewport, because the enclosing group scales it. -->
                    <aapt:attr name="android:fillColor">
                        <gradient
                            android:type="linear"
                            android:startX="12"
                            android:startY="1"
                            android:endX="12"
                            android:endY="23"
                            android:startColor="@color/splash_logo_gradient_start"
                            android:endColor="@color/splash_logo_gradient_end" />
                    </aapt:attr>
                </path>
            </group>
        </group>
    </group>
</vector>
"""


def build_xml(slogan_path, wordmark_path):
    slogan_block = ""
    if slogan_path:
        slogan_block = f"""
        <group android:name="slogan">
            <path
                android:name="sloganPath"
                android:fillColor="@color/splash_slogan"
                android:fillAlpha="1"
                android:pathData="{slogan_path}" />
        </group>"""
    return f"""<?xml version="1.0" encoding="utf-8"?>
<!--
    GENERATED by scripts/utils/generate-splash-brand.ps1 (S1706) - do not hand-edit.
    Regenerate after changing the `{STRING_KEY}` string or the generator's layout constants.
    Splash-screen centre content: the four-arrows logo in the launcher icon's blue, the
    "Fast Media Sorter" wordmark, and the slogan. Sized for the API-31 splash icon slot:
    a 288dp asset whose content stays inside the 192dp mask circle.
-->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt"
    android:width="288dp"
    android:height="288dp"
    android:viewportWidth="288"
    android:viewportHeight="288">
    <group android:name="splash">
        <group
            android:name="arrows"
            android:pivotX="{ARROWS_PIVOT_X}"
            android:pivotY="{ARROWS_PIVOT_Y:.1f}">
            <group
                android:scaleX="{ARROWS_SCALE}"
                android:scaleY="{ARROWS_SCALE}"
                android:translateX="{ARROWS_TX}"
                android:translateY="{ARROWS_TY}">
                <path
                    android:name="arrowsPath"
                    android:fillAlpha="1"
                    android:pathData="{ARROWS_PATH}">
                    <!-- The gradient runs in the path's own 24-unit space, not the 288
                         viewport, because the enclosing group scales it. -->
                    <aapt:attr name="android:fillColor">
                        <gradient
                            android:type="linear"
                            android:startX="12"
                            android:startY="1"
                            android:endX="12"
                            android:endY="23"
                            android:startColor="@color/splash_logo_gradient_start"
                            android:endColor="@color/splash_logo_gradient_end" />
                    </aapt:attr>
                </path>
            </group>
        </group>
        <group android:name="wordmark" android:translateY="{WORDMARK_TRANSLATE_Y}">
            <path
                android:name="wordmarkPath"
                android:fillColor="@color/splash_content"
                android:fillAlpha="1"
                android:pathData="{wordmark_path}" />
        </group>{slogan_block}
    </group>
</vector>
"""


def locale_of(values_dir):
    name = os.path.basename(values_dir)
    return "" if name == "values" else name[len("values-"):]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--res-root", required=True)
    ap.add_argument("--wordmark", required=True)
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--arrows-only", action="store_true")
    args = ap.parse_args()

    if args.arrows_only:
        target = os.path.join(args.res_root, "drawable", "ic_splash_app_brand.xml")
        xml = build_arrows_only_xml()
        current = open(target, encoding="utf-8").read() if os.path.isfile(target) else None
        if current == xml:
            print("arrows-only: up to date")
            return 0
        if args.check:
            print("arrows-only: default would change", file=sys.stderr)
            return 1
        os.makedirs(os.path.dirname(target), exist_ok=True)
        with open(target, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(xml)
        print("arrows-only: wrote default")
        return 0

    wordmark_path = open(args.wordmark, encoding="utf-8").read().strip()
    values_dirs = sorted(
        os.path.join(args.res_root, d)
        for d in os.listdir(args.res_root)
        if d == "values" or d.startswith("values-")
    )

    changed, failures = [], []
    for values_dir in values_dirs:
        strings_path = os.path.join(values_dir, "strings.xml")
        if not os.path.isfile(strings_path):
            continue
        slogan = read_slogan(strings_path)
        locale = locale_of(values_dir)
        if slogan is None:
            continue
        size, slogan_path, width = fit_line(slogan)
        if size is None:
            failures.append(
                f"{locale or 'default'}: {slogan!r} does not fit the mask circle at any "
                f"size down to {SLOGAN_SIZES[-1]} (widest run {width:.0f} units). "
                f"Shorten the translation."
            )
            continue
        target_dir = os.path.join(args.res_root, "drawable" if not locale else f"drawable-{locale}")
        target = os.path.join(target_dir, "ic_splash_app_brand.xml")
        xml = build_xml(slogan_path, wordmark_path)
        current = open(target, encoding="utf-8").read() if os.path.isfile(target) else None
        if current == xml:
            continue
        changed.append(f"{locale or 'default'} (slogan size {size})")
        if not args.check:
            os.makedirs(target_dir, exist_ok=True)
            with open(target, "w", encoding="utf-8", newline="\n") as fh:
                fh.write(xml)

    for line in failures:
        print(f"FAIL {line}", file=sys.stderr)
    for line in changed:
        print(f"{'would write' if args.check else 'wrote'} {line}")
    if failures:
        return 1
    if args.check and changed:
        return 1
    if not changed:
        print("splash brand drawables are in sync")
    return 0


if __name__ == "__main__":
    sys.exit(main())
