#!/usr/bin/env python
"""Compose the Play feature graphic from store_assets/design_brief.md section 2 (S2597).

Writes play/listing/<locale>/images/featureGraphic.png for every locale folder that already
carries an images/ directory, and writes the en-US render to
fastlane/metadata/android/en-US/images/featureGraphic.png as well.

WHY BOTH TREES COME OUT OF ONE RUN. play/listing/ and fastlane/metadata/android/ are deliberately
separate publication sources, but the reason recorded in play/listing/README.md is entirely about
TEXT: IzzyOnDroid requires an "Anti-Features / non-free dependencies" block that is dead weight on
Google Play. Nothing in that reason touches an image, so the two storefronts show one artwork - and
they are written by one run rather than kept in step by hand, because two committed copies of the
same picture drift the first time somebody redraws one of them.

WHY THIS SCRIPT EXISTS AT ALL. Until this ticket the tree held exactly one feature graphic, under
fastlane/, generated by a .NET composite in S0215 and never looked at afterwards: its wordmark ran
off the right edge as "FastMediaSorte" and its second tagline line as "Local - SMB - FTP - SFTP -
Clou". That is precisely the acceptance criterion the design brief states - "All three locale
headlines fit without truncation at 1024 x 500 px" - and nothing measured it, because a PNG has no
build to fail. Here the criterion is the code: fit_text() shrinks and wraps within a real measured
column and REFUSES rather than drawing a clipped string, so a headline that cannot fit stops the
run instead of shipping.

The layout follows the brief: app icon in the left 30%, headline and sub-headline in the centre
40%, phone mockup in the right 30%, dark navy background.

The mockup is cut out of the composed screenshot of the `browse` slot rather than read from
temp/play-shots/, which is a gitignored scratch area whose raw shots do not survive (S2398) - a
composer that depended on them would stop being reproducible the moment temp/ was cleaned. The
slot's ordinal is resolved through play/listing/captions.json instead of assuming a file name, and
the caption band that compose-play-screenshots.py adds above the frame is located by scanning for
where its colour ends, never by a pixel constant that would silently mis-crop after S2573 changed
the band's height rule.

Usage:
    python scripts/release/compose-feature-graphic.py

Exit codes:
    0   every locale composed and written.
    1   the composition is at fault - a headline that does not fit its column at the smallest size
        the brief allows, a missing icon, or no composed `browse` screenshot to cut the mockup from.
    2   the run could not happen: no Cyrillic-capable bold TTF is installed on this machine.
"""
import json
import os
import sys

from PIL import Image, ImageDraw, ImageFilter, ImageFont

if '--help' in sys.argv or '-h' in sys.argv:
    print(__doc__)
    sys.exit(0)

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
LISTING_ROOT = os.path.join(REPO_ROOT, 'play', 'listing')
CAPTIONS_PATH = os.path.join(LISTING_ROOT, 'captions.json')
ICON_PATH = os.path.join(REPO_ROOT, 'store_assets', 'icon_512.png')
FASTLANE_GRAPHIC = os.path.join(
    REPO_ROOT, 'fastlane', 'metadata', 'android', 'en-US', 'images', 'featureGraphic.png')

# Play's feature graphic slot. Fixed by Google, not a preference.
CANVAS_W, CANVAS_H = 1024, 500

# design_brief.md section 2: dark theme, #0D1B2A navy to #0A2463 deep blue.
BG_TOP = (13, 27, 42)
BG_BOTTOM = (10, 36, 99)
TEXT_COLOR = (255, 255, 255)
SUB_COLOR = (144, 202, 249)
FRAME_COLOR = (66, 165, 245)

# design_brief.md section 2, "Layout (left to right)" - the three columns as fractions of the width.
LEFT_FRACTION = 0.30
CENTRE_FRACTION = 0.40

# The brief asks for a bold headline of at least 48 px in the source file. The floor is lower
# because the source file IS the output here: a 1024 px canvas gives the centre column ~380 px, and
# holding 48 px there would refuse the Russian headline outright. 34 px still reads at the size Play
# renders the banner, and anything under it fails the run rather than being drawn small.
HEADLINE_SIZE_MAX = 54
HEADLINE_SIZE_MIN = 34
HEADLINE_MAX_LINES = 3
SUB_SIZE_MAX = 26
SUB_SIZE_MIN = 16
SUB_MAX_LINES = 1

# The slot whose composed frame supplies the phone mockup. The brief asks for "the Browse / Sort
# screen"; this is that slot's stable id in captions.json.
MOCKUP_SLOT_ID = 'browse'

# Two channels of tolerance when deciding "still the same flat colour". The caption band and the
# canvas padding are both painted flat, so anything past a couple of levels is content.
FLAT_TOLERANCE = 12

BOLD_FONT_CANDIDATES = [
    r'C:\Windows\Fonts\segoeuib.ttf',
    r'C:\Windows\Fonts\arialbd.ttf',
]
REGULAR_FONT_CANDIDATES = [
    r'C:\Windows\Fonts\segoeui.ttf',
    r'C:\Windows\Fonts\arial.ttf',
]

# design_brief.md section 2, "Headline copy" and "Sub-headline". One table, so the copy has a single
# home; the sub-headline is deliberately identical across locales, as the brief states.
SUB_HEADLINE = 'Local \u00b7 NAS \u00b7 Cloud'
HEADLINES = {
    'en-US': 'Sort photos & videos in seconds',
    'ru-RU': '\u0421\u043e\u0440\u0442\u0438\u0440\u0443\u0439 \u0444\u043e\u0442\u043e '
             '\u0438 \u0432\u0438\u0434\u0435\u043e \u0437\u0430 '
             '\u0441\u0435\u043a\u0443\u043d\u0434\u044b',
    'uk-UA': '\u0421\u043e\u0440\u0442\u0443\u0439 \u0444\u043e\u0442\u043e \u0442\u0430 '
             '\u0432\u0456\u0434\u0435\u043e \u0437\u0430 '
             '\u0441\u0435\u043a\u0443\u043d\u0434\u0438',
}


class CompositionError(Exception):
    """The graphic cannot be drawn as specified - exit 1, never a clipped drawing."""


class ToolingError(Exception):
    """The run cannot happen on this machine - exit 2, the composition is not implicated."""


def resolve_font_path(candidates):
    for path in candidates:
        if os.path.exists(path):
            return path
    raise ToolingError(
        'No Cyrillic-capable TTF found. Tried: ' + '; '.join(candidates))


def wrap_to_width(draw, text, font, max_width):
    """Greedy word wrap. Returns the lines, or None when one word alone is already too wide."""
    lines = []
    current = ''
    for word in text.split():
        if draw.textlength(word, font=font) > max_width:
            return None
        candidate = word if not current else current + ' ' + word
        if draw.textlength(candidate, font=font) <= max_width:
            current = candidate
        else:
            lines.append(current)
            current = word
    if current:
        lines.append(current)
    return lines


def fit_text(draw, text, font_path, max_width, max_lines, size_max, size_min):
    """Largest size at which `text` wraps into at most `max_lines` inside `max_width`.

    Returns (font, lines), or (None, None) when it does not fit even at size_min. The caller turns
    that into a refusal: this is the brief's "fit without truncation" criterion, and answering it
    with a clipped drawing is the defect the whole ticket exists to remove.
    """
    for size in range(size_max, size_min - 1, -1):
        font = ImageFont.truetype(font_path, size)
        lines = wrap_to_width(draw, text, font, max_width)
        if lines is not None and len(lines) <= max_lines:
            return font, lines
    return None, None


def is_flat_match(pixel, reference):
    return all(abs(int(a) - int(b)) <= FLAT_TOLERANCE for a, b in zip(pixel[:3], reference[:3]))


def detect_band_bottom(img):
    """First row from the top that is no longer part of the flat caption band.

    compose-play-screenshots.py paints the localized caption onto a flat band ADDED above the
    frame, and its height follows the canvas height (S2573), so it is not a constant this script
    may carry. The probe reads the two extreme edge columns rather than the middle: the caption
    text is centred and crosses the centre column, which would end the scan on the first glyph and
    leave most of the band in the mockup. A frame with no band answers with a small number and
    loses nothing - the scan simply stops at the first row of real content.
    """
    pixels = img.convert('RGB').load()
    probes = (2, img.width - 3)
    reference = pixels[probes[0], 0]
    for y in range(img.height):
        if not all(is_flat_match(pixels[x, y], reference) for x in probes):
            return y
    return 0


def trim_uniform_border(img):
    """Drop every fully flat border row and column, using the top-left pixel as the reference.

    The screenshot composer pads a tall frame onto a wider canvas to respect Play's 2:1 aspect cap,
    so a composed file carries background either side of the frame. Judging a whole line rather
    than one probe pixel is what makes this safe: screenshot content that happens to match the
    padding colour at one point does not match it down an entire column.
    """
    pixels = img.load()
    reference = pixels[0, 0]
    rows = range(0, img.height, 4)
    cols = range(0, img.width, 4)

    def flat_column(x):
        return all(is_flat_match(pixels[x, y], reference) for y in rows)

    def flat_row(y):
        return all(is_flat_match(pixels[x, y], reference) for x in cols)

    left = 0
    while left < img.width - 1 and flat_column(left):
        left += 1
    right = img.width - 1
    while right > left and flat_column(right):
        right -= 1
    top = 0
    while top < img.height - 1 and flat_row(top):
        top += 1
    bottom = img.height - 1
    while bottom > top and flat_row(bottom):
        bottom -= 1
    return img.crop((left, top, right + 1, bottom + 1))


def extract_mockup(composed):
    """Cut the bare phone frame out of a composed store screenshot."""
    img = composed.convert('RGB')
    band_bottom = detect_band_bottom(img)
    body = img.crop((0, band_bottom, img.width, img.height))
    return trim_uniform_border(body)


def rounded(img, radius):
    """Return `img` with rounded corners as an RGBA image."""
    mask = Image.new('L', img.size, 0)
    ImageDraw.Draw(mask).rounded_rectangle([(0, 0), (img.width - 1, img.height - 1)],
                                           radius=radius, fill=255)
    out = img.convert('RGBA')
    out.putalpha(mask)
    return out


def draw_background(canvas):
    """Vertical navy gradient with a soft glow behind the icon column."""
    draw = ImageDraw.Draw(canvas)
    for y in range(CANVAS_H):
        ratio = y / (CANVAS_H - 1)
        draw.line([(0, y), (CANVAS_W, y)],
                  fill=tuple(int(a + (b - a) * ratio) for a, b in zip(BG_TOP, BG_BOTTOM)))
    glow = Image.new('RGB', (CANVAS_W, CANVAS_H), (0, 0, 0))
    ImageDraw.Draw(glow).ellipse(
        [(-120, 40), (int(CANVAS_W * LEFT_FRACTION) + 120, CANVAS_H - 40)], fill=(24, 64, 132))
    canvas.paste(Image.blend(canvas, glow, 0.35).filter(ImageFilter.GaussianBlur(60)), (0, 0))
    return canvas


def compose(locale, headline, icon, mockup, bold_path, regular_path):
    """Render one locale's 1024x500 graphic. Raises CompositionError when a text cannot fit."""
    canvas = draw_background(Image.new('RGB', (CANVAS_W, CANVAS_H), BG_TOP))
    draw = ImageDraw.Draw(canvas)

    left_w = int(CANVAS_W * LEFT_FRACTION)
    centre_w = int(CANVAS_W * CENTRE_FRACTION)
    centre_x = left_w

    icon_size = 200
    icon_scaled = rounded(icon.convert('RGB').resize((icon_size, icon_size), Image.LANCZOS),
                          radius=int(icon_size * 0.22))
    canvas.paste(icon_scaled, ((left_w - icon_size) // 2, (CANVAS_H - icon_size) // 2), icon_scaled)

    text_pad = 18
    text_w = centre_w - text_pad * 2
    headline_font, headline_lines = fit_text(
        draw, headline, bold_path, text_w, HEADLINE_MAX_LINES, HEADLINE_SIZE_MAX, HEADLINE_SIZE_MIN)
    if headline_font is None:
        raise CompositionError(
            f"{locale}: headline does not fit {text_w}px at {HEADLINE_SIZE_MIN}px in "
            f"{HEADLINE_MAX_LINES} lines: {headline!r}")
    sub_font, sub_lines = fit_text(
        draw, SUB_HEADLINE, regular_path, text_w, SUB_MAX_LINES, SUB_SIZE_MAX, SUB_SIZE_MIN)
    if sub_font is None:
        raise CompositionError(
            f"{locale}: sub-headline does not fit {text_w}px: {SUB_HEADLINE!r}")

    headline_step = int(headline_font.size * 1.16)
    sub_step = int(sub_font.size * 1.3)
    block_h = headline_step * len(headline_lines) + sub_step
    y = (CANVAS_H - block_h) // 2
    for line in headline_lines:
        draw.text((centre_x + text_pad, y), line, font=headline_font, fill=TEXT_COLOR)
        y += headline_step
    for line in sub_lines:
        draw.text((centre_x + text_pad, y + sub_step // 5), line, font=sub_font, fill=SUB_COLOR)

    right_x = centre_x + centre_w
    right_w = CANVAS_W - right_x
    margin = 26
    target_h = CANVAS_H - margin * 2
    scale = target_h / mockup.height
    if mockup.width * scale > right_w - margin * 2:
        scale = (right_w - margin * 2) / mockup.width
    phone = mockup.resize((max(1, int(mockup.width * scale)), max(1, int(mockup.height * scale))),
                          Image.LANCZOS)
    phone = rounded(phone, radius=max(6, int(phone.width * 0.09)))
    phone_x = right_x + (right_w - phone.width) // 2
    phone_y = (CANVAS_H - phone.height) // 2
    canvas.paste(phone, (phone_x, phone_y), phone)
    ImageDraw.Draw(canvas).rounded_rectangle(
        [(phone_x, phone_y), (phone_x + phone.width - 1, phone_y + phone.height - 1)],
        radius=max(6, int(phone.width * 0.09)), outline=FRAME_COLOR, width=3)
    return canvas


def mockup_ordinal():
    """1-based position of the mockup slot in captions.json, which is the composed file's number."""
    with open(CAPTIONS_PATH, encoding='utf-8') as handle:
        slots = json.load(handle)['slots']
    for index, slot in enumerate(slots):
        if slot['id'] == MOCKUP_SLOT_ID:
            return index + 1
    raise CompositionError(f"captions.json declares no '{MOCKUP_SLOT_ID}' slot")


def resolve_mockup_source(locale, ordinal):
    """The locale's own composed frame, falling back to the default language's."""
    for candidate_locale in (locale, 'en-US'):
        path = os.path.join(LISTING_ROOT, candidate_locale, 'images', 'phoneScreenshots',
                            f"{ordinal:02d}.png")
        if os.path.exists(path):
            return path
    return None


def locales_with_images():
    return sorted(name for name in os.listdir(LISTING_ROOT)
                  if os.path.isdir(os.path.join(LISTING_ROOT, name, 'images')))


def main():
    bold_path = resolve_font_path(BOLD_FONT_CANDIDATES)
    regular_path = resolve_font_path(REGULAR_FONT_CANDIDATES)
    if not os.path.exists(ICON_PATH):
        raise CompositionError(f"icon not found: {ICON_PATH}")
    icon = Image.open(ICON_PATH)
    ordinal = mockup_ordinal()

    written = 0
    for locale in locales_with_images():
        headline = HEADLINES.get(locale)
        if headline is None:
            print(f"  {locale}: skipped - design_brief.md carries no headline for this locale")
            continue
        source = resolve_mockup_source(locale, ordinal)
        if source is None:
            raise CompositionError(
                f"{locale}: no composed '{MOCKUP_SLOT_ID}' screenshot at ordinal {ordinal:02d} to "
                f"cut the mockup from - run compose-play-screenshots.py first")
        mockup = extract_mockup(Image.open(source))
        graphic = compose(locale, headline, icon, mockup, bold_path, regular_path)
        out_path = os.path.join(LISTING_ROOT, locale, 'images', 'featureGraphic.png')
        graphic.save(out_path)
        written += 1
        print(f"  {locale}: {os.path.relpath(out_path, REPO_ROOT)} ({graphic.width}x{graphic.height})")
        if locale == 'en-US':
            graphic.save(FASTLANE_GRAPHIC)
            print(f"  {locale}: {os.path.relpath(FASTLANE_GRAPHIC, REPO_ROOT)} (same artwork)")
    if written == 0:
        raise CompositionError('no locale composed - play/listing carries no images/ folder')
    print(f"compose-feature-graphic: {written} locale(s) composed")


if __name__ == '__main__':
    try:
        main()
    except ToolingError as error:
        print(f"ERROR: {error}")
        sys.exit(2)
    except CompositionError as error:
        print(f"ERROR: {error}")
        sys.exit(1)
