#requires -Version 7.0
<#
.SYNOPSIS
    S1211 - render the site's language list from the app's locale declaration.

.DESCRIPTION
    Parses app_v2/src/main/res/xml/locales_config.xml and writes _data/languages.yml, the only
    language list the Jekyll site reads (site.data.languages). The SET of languages comes from the
    XML alone (S1211 ADR-2: a second list is a second way for the app and the site to diverge);
    this script only adds what the XML cannot carry - the endonym and the text direction - from the
    table below, keyed by the declared tag.

    Each entry:
      code     the BCP-47 tag exactly as declared (zh-Hans)
      slug     the filename suffix: the tag lowercased, hyphen kept (zh-hans)
      endonym  the language's name in that language
      dir      rtl or ltr

    A declared locale missing from the table is refused rather than rendered with a guessed name,
    because the switcher labels every language by its endonym.

.PARAMETER OutFile
    Where to write. Defaults to _data/languages.yml under the repository root. The freshness gate
    passes a temporary path here and compares.

.PARAMETER LocalesConfig
    Override for the source XML; defaults to the app's declaration.

.EXAMPLE
    pwsh -NoProfile -File scripts/docs/generate-site-languages.ps1

.NOTES
    Exit codes:
      0  written
      1  a declared locale has no endonym entry in the table
      2  the XML is missing or unparseable, or declares no locale
#>
[CmdletBinding()]
param(
    [string] $RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path,
    [string] $LocalesConfig,
    [string] $OutFile
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

if (-not $LocalesConfig) { $LocalesConfig = Join-Path $RepoRoot 'app_v2/src/main/res/xml/locales_config.xml' }
if (-not $OutFile) { $OutFile = Join-Path $RepoRoot '_data/languages.yml' }

$languageTable = @{
    'en'      = @{ endonym = 'English';    dir = 'ltr' }
    'zh-Hans' = @{ endonym = '中文';        dir = 'ltr' }
    'hi'      = @{ endonym = 'हिन्दी';       dir = 'ltr' }
    'es'      = @{ endonym = 'Español';    dir = 'ltr' }
    'fr'      = @{ endonym = 'Français';   dir = 'ltr' }
    'ar'      = @{ endonym = 'العربية';    dir = 'rtl' }
    'bn'      = @{ endonym = 'বাংলা';       dir = 'ltr' }
    'pt'      = @{ endonym = 'Português';  dir = 'ltr' }
    'ru'      = @{ endonym = 'Русский';    dir = 'ltr' }
    'ur'      = @{ endonym = 'اردو';       dir = 'rtl' }
    'uk'      = @{ endonym = 'Українська'; dir = 'ltr' }
    'de'      = @{ endonym = 'Deutsch';    dir = 'ltr' }
    'it'      = @{ endonym = 'Italiano';   dir = 'ltr' }
}

if (-not (Test-Path -LiteralPath $LocalesConfig)) {
    Write-Host "generate-site-languages: source missing: $LocalesConfig" -ForegroundColor Red
    exit 2
}

try {
    [xml]$xml = Get-Content -LiteralPath $LocalesConfig -Raw -Encoding UTF8
} catch {
    Write-Host "generate-site-languages: cannot parse $LocalesConfig - $($_.Exception.Message)" -ForegroundColor Red
    exit 2
}

$androidNs = 'http://schemas.android.com/apk/res/android'
$tags = @($xml.DocumentElement.ChildNodes |
        Where-Object { $_.NodeType -eq 'Element' -and $_.LocalName -eq 'locale' } |
        ForEach-Object { $_.GetAttribute('name', $androidNs) } |
        Where-Object { $_ })

if ($tags.Count -eq 0) {
    Write-Host "generate-site-languages: $LocalesConfig declares no locale" -ForegroundColor Red
    exit 2
}

$unknown = @($tags | Where-Object { -not $languageTable.ContainsKey($_) })
if ($unknown.Count -gt 0) {
    Write-Host ("generate-site-languages: no endonym entry for {0} - add a row to the table in {1}" -f
        ($unknown -join ', '), $PSCommandPath) -ForegroundColor Red
    exit 1
}

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add('# GENERATED by scripts/docs/generate-site-languages.ps1 from')
$lines.Add('# app_v2/src/main/res/xml/locales_config.xml - do not edit; rerun the generator.')
foreach ($tag in $tags) {
    $row = $languageTable[$tag]
    $lines.Add("- code: $tag")
    $lines.Add("  slug: $($tag.ToLowerInvariant())")
    $lines.Add("  endonym: $($row.endonym)")
    $lines.Add("  dir: $($row.dir)")
}

$outDir = Split-Path -Parent $OutFile
if ($outDir -and -not (Test-Path -LiteralPath $outDir)) {
    New-Item -ItemType Directory -Path $outDir -Force | Out-Null
}
$utf8NoBom = [System.Text.UTF8Encoding]::new($false)
[System.IO.File]::WriteAllText($OutFile, (($lines -join "`n") + "`n"), $utf8NoBom)
Write-Host "generate-site-languages: wrote $($tags.Count) language(s) to $OutFile"
exit 0
