# S1495 - licence manifest for the OSS notice generator.
#
# Keyed by "group:artifact" - never by version, because a version bump must not require a
# manifest edit while a new dependency must.
#
# A shipping coordinate missing from this file is a FATAL error in
# scripts/docs/generate-oss-notices.ps1, not a skipped row. That refusal is the whole
# mechanism: it is what stops a newly added dependency from silently going unlisted, which
# is exactly how the published page came to name 2 libraries out of 97 (S1495 ADR-3).
#
# Adding a dependency to app_v2/build.gradle.kts or wear/build.gradle.kts means adding it
# here in the same change.
#
# Fields
#   Name        human-readable library name shown on the page
#   Spdx        SPDX identifier, or the exact proprietary licence name when not OSS
#   LicenseUrl  canonical licence text
#   SourceUrl   project source, or the vendor's terms page for a proprietary SDK
#   Oss         $false marks a component distributed under vendor terms rather than an
#               open source licence; the page groups those separately instead of calling
#               them open source
#   Note        one line shown on the page when the licence needs a qualifier
#   Transitive  $true when no declaration names it - it arrives through another artifact
#   Via         the coordinate that pulls a transitive entry in
#   Bundled     $true for a binary shipped from app_v2/libs rather than resolved from Maven
#   ShippedInOverride  flavor list for an entry the parser cannot see (bundled binaries)
#
# Every value below was taken from the project's own LICENSE file or the <licenses> block of
# the pinned version's POM, verified 2026-08-10. Two long-published claims were wrong and are
# corrected here: SMBJ and epub4j are Apache-2.0, not LGPL-2.1 (see S1562 for the same error
# still shipping inside the app).

@{
    # ── AndroidX ──────────────────────────────────────────────────────────────────────────
    'androidx.activity:activity-compose'        = @{ Name = 'AndroidX Activity Compose';        Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://android.googlesource.com/platform/frameworks/support/' }
    'androidx.activity:activity-ktx'            = @{ Name = 'AndroidX Activity KTX';            Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://android.googlesource.com/platform/frameworks/support/' }
    'androidx.appcompat:appcompat'              = @{ Name = 'AndroidX AppCompat';               Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://android.googlesource.com/platform/frameworks/support/' }
    'androidx.browser:browser'                  = @{ Name = 'AndroidX Browser';                 Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://android.googlesource.com/platform/frameworks/support/' }
    'androidx.camera:camera-camera2'            = @{ Name = 'AndroidX CameraX Camera2';         Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://android.googlesource.com/platform/frameworks/support/' }
    'androidx.camera:camera-core'               = @{ Name = 'AndroidX CameraX Core';            Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://android.googlesource.com/platform/frameworks/support/' }
    'androidx.camera:camera-extensions'         = @{ Name = 'AndroidX CameraX Extensions';      Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://android.googlesource.com/platform/frameworks/support/' }
    'androidx.camera:camera-lifecycle'          = @{ Name = 'AndroidX CameraX Lifecycle';       Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://android.googlesource.com/platform/frameworks/support/' }
    'androidx.camera:camera-video'              = @{ Name = 'AndroidX CameraX Video';           Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://android.googlesource.com/platform/frameworks/support/' }
    'androidx.camera:camera-view'               = @{ Name = 'AndroidX CameraX View';            Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://android.googlesource.com/platform/frameworks/support/' }
    'androidx.compose.material:material-icons-core'     = @{ Name = 'Jetpack Compose Material Icons Core';     Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://android.googlesource.com/platform/frameworks/support/' }
    'androidx.compose.material:material-icons-extended' = @{ Name = 'Jetpack Compose Material Icons Extended'; Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://android.googlesource.com/platform/frameworks/support/' }
    'androidx.compose.material3:material3'      = @{ Name = 'Jetpack Compose Material 3';       Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://android.googlesource.com/platform/frameworks/support/' }
    'androidx.compose.ui:ui'                    = @{ Name = 'Jetpack Compose UI';               Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://android.googlesource.com/platform/frameworks/support/' }
    'androidx.compose.ui:ui-graphics'           = @{ Name = 'Jetpack Compose UI Graphics';      Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://android.googlesource.com/platform/frameworks/support/' }
    'androidx.compose.ui:ui-tooling-preview'    = @{ Name = 'Jetpack Compose UI Tooling Preview'; Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://android.googlesource.com/platform/frameworks/support/' }
    'androidx.constraintlayout:constraintlayout' = @{ Name = 'AndroidX ConstraintLayout';       Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://github.com/androidx/constraintlayout' }
    'androidx.core:core-ktx'                    = @{ Name = 'AndroidX Core KTX';                Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://android.googlesource.com/platform/frameworks/support/' }
    'androidx.credentials:credentials'          = @{ Name = 'AndroidX Credentials';             Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://android.googlesource.com/platform/frameworks/support/' }
    'androidx.credentials:credentials-play-services-auth' = @{ Name = 'AndroidX Credentials Play Services Auth'; Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://android.googlesource.com/platform/frameworks/support/' }
    'androidx.datastore:datastore-preferences'  = @{ Name = 'AndroidX DataStore Preferences';   Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://android.googlesource.com/platform/frameworks/support/' }
    'androidx.documentfile:documentfile'        = @{ Name = 'AndroidX DocumentFile';            Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://android.googlesource.com/platform/frameworks/support/' }
    'androidx.exifinterface:exifinterface'      = @{ Name = 'AndroidX ExifInterface';           Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://android.googlesource.com/platform/frameworks/support/' }
    'androidx.fragment:fragment-ktx'            = @{ Name = 'AndroidX Fragment KTX';            Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://android.googlesource.com/platform/frameworks/support/' }
    'androidx.hilt:hilt-navigation-compose'     = @{ Name = 'AndroidX Hilt Navigation Compose'; Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://android.googlesource.com/platform/frameworks/support/' }
    'androidx.hilt:hilt-work'                   = @{ Name = 'AndroidX Hilt WorkManager';        Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://android.googlesource.com/platform/frameworks/support/' }
    'androidx.lifecycle:lifecycle-livedata-ktx' = @{ Name = 'AndroidX Lifecycle LiveData KTX';  Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://android.googlesource.com/platform/frameworks/support/' }
    'androidx.lifecycle:lifecycle-process'      = @{ Name = 'AndroidX Lifecycle Process';       Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://android.googlesource.com/platform/frameworks/support/' }
    'androidx.lifecycle:lifecycle-runtime-compose' = @{ Name = 'AndroidX Lifecycle Runtime Compose'; Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://android.googlesource.com/platform/frameworks/support/' }
    'androidx.lifecycle:lifecycle-runtime-ktx'  = @{ Name = 'AndroidX Lifecycle Runtime KTX';   Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://android.googlesource.com/platform/frameworks/support/' }
    'androidx.lifecycle:lifecycle-viewmodel-compose' = @{ Name = 'AndroidX Lifecycle ViewModel Compose'; Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://android.googlesource.com/platform/frameworks/support/' }
    'androidx.lifecycle:lifecycle-viewmodel-ktx' = @{ Name = 'AndroidX Lifecycle ViewModel KTX'; Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://android.googlesource.com/platform/frameworks/support/' }
    'androidx.media3:media3-common'             = @{ Name = 'AndroidX Media3 Common';           Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://github.com/androidx/media' }
    'androidx.media3:media3-decoder'            = @{ Name = 'AndroidX Media3 Decoder';          Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://github.com/androidx/media' }
    'androidx.media3:media3-effect'             = @{ Name = 'AndroidX Media3 Effect';           Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://github.com/androidx/media' }
    'androidx.media3:media3-exoplayer'          = @{ Name = 'AndroidX Media3 ExoPlayer';        Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://github.com/androidx/media' }
    'androidx.media3:media3-exoplayer-dash'     = @{ Name = 'AndroidX Media3 ExoPlayer DASH';   Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://github.com/androidx/media' }
    'androidx.media3:media3-exoplayer-hls'      = @{ Name = 'AndroidX Media3 ExoPlayer HLS';    Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://github.com/androidx/media' }
    'androidx.media3:media3-exoplayer-midi'     = @{ Name = 'AndroidX Media3 ExoPlayer MIDI';   Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://github.com/androidx/media' }
    'androidx.media3:media3-exoplayer-rtsp'     = @{ Name = 'AndroidX Media3 ExoPlayer RTSP';   Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://github.com/androidx/media' }
    'androidx.media3:media3-session'            = @{ Name = 'AndroidX Media3 Session';          Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://github.com/androidx/media' }
    'androidx.media3:media3-transformer'        = @{ Name = 'AndroidX Media3 Transformer';      Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://github.com/androidx/media' }
    'androidx.media3:media3-ui'                 = @{ Name = 'AndroidX Media3 UI';               Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://github.com/androidx/media' }
    'androidx.mediarouter:mediarouter'          = @{ Name = 'AndroidX MediaRouter';             Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://android.googlesource.com/platform/frameworks/support/' }
    'androidx.paging:paging-runtime-ktx'        = @{ Name = 'AndroidX Paging Runtime KTX';      Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://android.googlesource.com/platform/frameworks/support/' }
    'androidx.print:print'                      = @{ Name = 'AndroidX Print';                   Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://android.googlesource.com/platform/frameworks/support/' }
    'androidx.profileinstaller:profileinstaller' = @{ Name = 'AndroidX ProfileInstaller';       Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://android.googlesource.com/platform/frameworks/support/' }
    'androidx.recyclerview:recyclerview'        = @{ Name = 'AndroidX RecyclerView';            Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://android.googlesource.com/platform/frameworks/support/' }
    'androidx.room:room-ktx'                    = @{ Name = 'AndroidX Room KTX';                Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://android.googlesource.com/platform/frameworks/support/' }
    'androidx.room:room-runtime'                = @{ Name = 'AndroidX Room Runtime';            Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://android.googlesource.com/platform/frameworks/support/' }
    'androidx.security:security-crypto'         = @{ Name = 'AndroidX Security Crypto';         Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://android.googlesource.com/platform/frameworks/support/' }
    'androidx.swiperefreshlayout:swiperefreshlayout' = @{ Name = 'AndroidX SwipeRefreshLayout'; Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://android.googlesource.com/platform/frameworks/support/' }
    'androidx.viewpager2:viewpager2'            = @{ Name = 'AndroidX ViewPager2';              Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://android.googlesource.com/platform/frameworks/support/' }
    'androidx.wear:wear'                        = @{ Name = 'AndroidX Wear';                    Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://android.googlesource.com/platform/frameworks/support/' }
    'androidx.wear.compose:compose-foundation'  = @{ Name = 'Wear Compose Foundation';          Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://android.googlesource.com/platform/frameworks/support/' }
    'androidx.wear.compose:compose-material'    = @{ Name = 'Wear Compose Material';            Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://android.googlesource.com/platform/frameworks/support/' }
    'androidx.wear.compose:compose-navigation'  = @{ Name = 'Wear Compose Navigation';          Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://android.googlesource.com/platform/frameworks/support/' }
    'androidx.work:work-runtime-ktx'            = @{ Name = 'AndroidX WorkManager Runtime KTX'; Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://android.googlesource.com/platform/frameworks/support/' }

    # ── Kotlin, DI, networking ────────────────────────────────────────────────────────────
    'org.jetbrains.kotlinx:kotlinx-coroutines-android'       = @{ Name = 'Kotlin Coroutines Android';       Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://github.com/Kotlin/kotlinx.coroutines' }
    'org.jetbrains.kotlinx:kotlinx-coroutines-core'          = @{ Name = 'Kotlin Coroutines Core';          Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://github.com/Kotlin/kotlinx.coroutines' }
    'org.jetbrains.kotlinx:kotlinx-coroutines-play-services' = @{ Name = 'Kotlin Coroutines Play Services'; Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://github.com/Kotlin/kotlinx.coroutines' }
    'com.google.dagger:hilt-android'            = @{ Name = 'Dagger Hilt Android';              Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://github.com/google/dagger' }
    'com.google.android.material:material'      = @{ Name = 'Material Components for Android';  Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://github.com/material-components/material-components-android' }
    'com.google.accompanist:accompanist-permissions' = @{ Name = 'Accompanist Permissions';     Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://github.com/google/accompanist' }
    'com.squareup.okhttp3:okhttp'               = @{ Name = 'OkHttp';                           Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://github.com/square/okhttp' }
    'com.squareup.retrofit2:retrofit'           = @{ Name = 'Retrofit';                         Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://github.com/square/retrofit' }
    'com.squareup.retrofit2:converter-gson'     = @{ Name = 'Retrofit Gson Converter';          Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://github.com/square/retrofit' }
    'com.jakewharton.timber:timber'             = @{ Name = 'Timber';                           Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://github.com/JakeWharton/timber' }
    'com.google.zxing:core'                     = @{ Name = 'ZXing Core';                       Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://github.com/zxing/zxing'; Note = 'Licence inherited from the zxing-parent POM; the core artifact declares no licences block of its own.' }

    # ── Media, imaging, documents ─────────────────────────────────────────────────────────
    'com.github.bumptech.glide:glide'           = @{ Name = 'Glide'; Spdx = 'BSD-2-Clause AND Apache-2.0 AND MIT'; LicenseUrl = 'https://raw.githubusercontent.com/bumptech/glide/master/LICENSE'; SourceUrl = 'https://github.com/bumptech/glide'; Note = 'Compound licence: BSD-2-Clause for Glide itself, Apache-2.0 for third_party/disklrucache, MIT for third_party/gif_decoder, plus two permissive grants in third_party/gif_encoder that have no SPDX identifier.' }
    'com.github.bumptech.glide:okhttp3-integration' = @{ Name = 'Glide OkHttp3 Integration';    Spdx = 'BSD-2-Clause'; LicenseUrl = 'https://raw.githubusercontent.com/bumptech/glide/master/LICENSE'; SourceUrl = 'https://github.com/bumptech/glide' }
    'io.coil-kt:coil-compose'                   = @{ Name = 'Coil for Compose';                 Spdx = 'Apache-2.0'; LicenseUrl = 'https://raw.githubusercontent.com/coil-kt/coil/main/LICENSE.txt'; SourceUrl = 'https://github.com/coil-kt/coil' }
    'com.github.chrisbanes:PhotoView'           = @{ Name = 'PhotoView';                        Spdx = 'Apache-2.0'; LicenseUrl = 'https://raw.githubusercontent.com/Baseflow/PhotoView/2.3.0/LICENSE'; SourceUrl = 'https://github.com/Baseflow/PhotoView'; Note = 'Published on JitPack under the original author coordinate; the canonical repository is Baseflow/PhotoView.' }
    'io.documentnode:epub4j-core'               = @{ Name = 'epub4j';                           Spdx = 'Apache-2.0'; LicenseUrl = 'https://raw.githubusercontent.com/documentnode/epub4j/main/LICENSE'; SourceUrl = 'https://github.com/documentnode/epub4j'; Note = 'Apache-2.0 per the repository LICENSE and the 4.2 POM. The upstream epublib project this is forked from declares LGPL in its parent POM, which is why the two are sometimes conflated.' }
    'io.noties.markwon:core'                    = @{ Name = 'Markwon';                          Spdx = 'Apache-2.0'; LicenseUrl = 'https://raw.githubusercontent.com/noties/Markwon/master/LICENSE'; SourceUrl = 'https://github.com/noties/Markwon' }
    'org.jsoup:jsoup'                           = @{ Name = 'jsoup';                            Spdx = 'MIT'; LicenseUrl = 'https://raw.githubusercontent.com/jhy/jsoup/master/LICENSE'; SourceUrl = 'https://github.com/jhy/jsoup' }
    'net.lingala.zip4j:zip4j'                   = @{ Name = 'Zip4j';                            Spdx = 'Apache-2.0'; LicenseUrl = 'https://raw.githubusercontent.com/srikanth-lingala/zip4j/master/LICENSE'; SourceUrl = 'https://github.com/srikanth-lingala/zip4j' }
    'cz.adaptech:tesseract4android'             = @{ Name = 'Tesseract4Android';                Spdx = 'Apache-2.0'; LicenseUrl = 'https://raw.githubusercontent.com/adaptech-cz/Tesseract4Android/master/LICENSE'; SourceUrl = 'https://github.com/adaptech-cz/Tesseract4Android'; Note = 'Bundles Tesseract OCR (Apache-2.0) and Leptonica (BSD-2-Clause) as native libraries.' }
    'com.github.TeamNewPipe:NewPipeExtractor'   = @{ Name = 'NewPipe Extractor';                Spdx = 'GPL-3.0-or-later'; LicenseUrl = 'https://raw.githubusercontent.com/TeamNewPipe/NewPipeExtractor/dev/LICENSE'; SourceUrl = 'https://github.com/TeamNewPipe/NewPipeExtractor'; Note = 'Copyleft without a linking exception, linked only into the sideload-only noLegal build. GPLv3 also obliges providing the corresponding source to recipients of that build - tracked as S1563.' }
    'org.khronos.openxr:openxr_loader_for_android' = @{ Name = 'OpenXR Loader for Android';     Spdx = 'Apache-2.0'; LicenseUrl = 'https://raw.githubusercontent.com/KhronosGroup/OpenXR-SDK/main/LICENSE'; SourceUrl = 'https://github.com/KhronosGroup/OpenXR-SDK-Source'; Note = 'Loader sources carry Apache-2.0 OR MIT. The shipped native library statically links jsoncpp (MIT), jnipp (MIT) and android-jni-wrappers (BSL-1.0).' }

    # ── Networking, storage, identity ─────────────────────────────────────────────────────
    'com.hierynomus:smbj'                       = @{ Name = 'SMBJ';                             Spdx = 'Apache-2.0'; LicenseUrl = 'https://www.apache.org/licenses/LICENSE-2.0'; SourceUrl = 'https://github.com/hierynomus/smbj'; Note = 'Apache-2.0 per the repository LICENSE_HEADER and the licences block of the 0.12.1 POM. The LGPL sometimes associated with SMB clients on Android belongs to jcifs-ng, a different library this project does not use.' }
    'com.github.mwiede:jsch'                    = @{ Name = 'JSch (mwiede fork)';               Spdx = 'BSD-3-Clause'; LicenseUrl = 'https://raw.githubusercontent.com/mwiede/jsch/master/LICENSE.txt'; SourceUrl = 'https://github.com/mwiede/jsch'; Note = 'The POM declares three licences: BSD-3-Clause for JSch, BSD-3-Clause for the bundled JZlib, ISC for the bundled jBCrypt.' }
    'commons-net:commons-net'                   = @{ Name = 'Apache Commons Net';               Spdx = 'Apache-2.0'; LicenseUrl = 'https://raw.githubusercontent.com/apache/commons-net/master/LICENSE.txt'; SourceUrl = 'https://github.com/apache/commons-net' }
    'org.nanohttpd:nanohttpd'                   = @{ Name = 'NanoHTTPD';                        Spdx = 'BSD-3-Clause'; LicenseUrl = 'https://raw.githubusercontent.com/NanoHttpd/nanohttpd/master/LICENSE.md'; SourceUrl = 'https://github.com/NanoHttpd/nanohttpd'; Note = 'Licence inherited from the nanohttpd-project POM; the artifact declares no licences block of its own.' }
    'com.dropbox.core:dropbox-core-sdk'         = @{ Name = 'Dropbox Java SDK';                 Spdx = 'MIT'; LicenseUrl = 'https://raw.githubusercontent.com/dropbox/dropbox-sdk-java/main/License.txt'; SourceUrl = 'https://github.com/dropbox/dropbox-sdk-java' }
    'com.microsoft.identity.client:msal'        = @{ Name = 'Microsoft Authentication Library';  Spdx = 'MIT'; LicenseUrl = 'https://raw.githubusercontent.com/AzureAD/microsoft-authentication-library-for-android/dev/LICENSE'; SourceUrl = 'https://github.com/AzureAD/microsoft-authentication-library-for-android' }
    'net.openid:appauth'                        = @{ Name = 'AppAuth for Android';              Spdx = 'Apache-2.0'; LicenseUrl = 'https://raw.githubusercontent.com/openid/AppAuth-Android/master/LICENSE'; SourceUrl = 'https://github.com/openid/AppAuth-Android' }
    'com.github.chuckerteam.chucker:library-no-op' = @{ Name = 'Chucker (no-op)';               Spdx = 'Apache-2.0'; LicenseUrl = 'https://raw.githubusercontent.com/ChuckerTeam/chucker/main/LICENSE.txt'; SourceUrl = 'https://github.com/ChuckerTeam/chucker' }

    # ── Toolchain shipped into the artifact ───────────────────────────────────────────────
    'com.android.tools:desugar_jdk_libs'        = @{ Name = 'Java 8+ API desugaring support';   Spdx = 'GPL-2.0-with-classpath-exception'; LicenseUrl = 'https://github.com/google/desugar_jdk_libs/blob/master/LICENSE'; SourceUrl = 'https://github.com/google/desugar_jdk_libs'; Note = 'The Classpath Exception removes the copyleft effect of linking, so using this library does not oblige us to release the application source. The exception must be named alongside the GPL or the entry reads as a stronger obligation than it is.' }

    # ── Transitive, named by no declaration ───────────────────────────────────────────────
    'org.bouncycastle:bcprov-jdk18on'           = @{ Name = 'Bouncy Castle Provider'; Spdx = 'MIT'; LicenseUrl = 'https://www.bouncycastle.org/licence.html'; SourceUrl = 'https://github.com/bcgit/bc-java'; Transitive = $true; Via = 'com.hierynomus:smbj'; Note = 'Published as the "Bouncy Castle Licence"; the text is verbatim MIT with their copyright, so scanners report NOASSERTION and the identifier is set by hand.' }

    # ── Bundled binary, carries no Maven coordinate ───────────────────────────────────────
    'local:fms-ffmpeg-dts'                      = @{ Name = 'FFmpeg (custom Media3 decoder build)'; Spdx = 'LGPL-2.1-or-later'; LicenseUrl = 'https://www.gnu.org/licenses/old-licenses/lgpl-2.1.html'; SourceUrl = 'https://github.com/androidx/media/tree/release/libraries/decoder_ffmpeg'; Bundled = $true; ShippedInOverride = @('standard', 'noLegal', 'legacy', 'vr'); Note = 'Built from FFmpeg sources by scripts/builders/build-ffmpeg-dts.sh and shipped as app_v2/libs/fms-ffmpeg-dts.aar. Its configure invocation passes neither --enable-gpl nor --enable-nonfree and disables postproc, the GPL component, so the produced binary is LGPL-2.1-or-later.' }

    # ── Vendor terms, not open source ─────────────────────────────────────────────────────
    'com.google.android.gms:play-services-auth' = @{ Name = 'Google Play services Auth';        Spdx = 'Android Software Development Kit License'; LicenseUrl = 'https://developer.android.com/studio/terms.html'; SourceUrl = 'https://developers.google.com/android/guides/setup'; Oss = $false }
    'com.google.android.gms:play-services-cast-framework' = @{ Name = 'Google Cast Framework';  Spdx = 'Android Software Development Kit License'; LicenseUrl = 'https://developer.android.com/studio/terms.html'; SourceUrl = 'https://developers.google.com/cast'; Oss = $false }
    'com.google.android.gms:play-services-wearable' = @{ Name = 'Google Play services Wearable'; Spdx = 'Android Software Development Kit License'; LicenseUrl = 'https://developer.android.com/studio/terms.html'; SourceUrl = 'https://developers.google.com/android/guides/setup'; Oss = $false }
    'com.google.android.libraries.identity.googleid:googleid' = @{ Name = 'Google ID for Credential Manager'; Spdx = 'Android Software Development Kit License'; LicenseUrl = 'https://developer.android.com/studio/terms.html'; SourceUrl = 'https://developer.android.com/identity/sign-in/credential-manager-siwg'; Oss = $false }
    'com.google.mlkit:language-id'              = @{ Name = 'ML Kit Language Identification';   Spdx = 'ML Kit Terms of Service'; LicenseUrl = 'https://developers.google.com/ml-kit/terms'; SourceUrl = 'https://developers.google.com/ml-kit/language/identification'; Oss = $false }
    'com.google.mlkit:translate'                = @{ Name = 'ML Kit Translation';               Spdx = 'ML Kit Terms of Service'; LicenseUrl = 'https://developers.google.com/ml-kit/terms'; SourceUrl = 'https://developers.google.com/ml-kit/language/translation'; Oss = $false }
    'com.google.android.play:feature-delivery-ktx' = @{ Name = 'Play Feature Delivery';         Spdx = 'Play Core Software Development Kit Terms of Service'; LicenseUrl = 'https://developer.android.com/guide/playcore/license'; SourceUrl = 'https://developer.android.com/guide/playcore'; Oss = $false }
    'com.google.android.play:review-ktx'         = @{ Name = 'Play In-App Review';              Spdx = 'Play Core Software Development Kit Terms of Service'; LicenseUrl = 'https://developer.android.com/guide/playcore/license'; SourceUrl = 'https://developer.android.com/guide/playcore'; Oss = $false }
}
