<#
.SYNOPSIS
    Puts a "last edited" stamp (yy.MM.dd HH:mm) at the top of every Markdown and HTML document.

.DESCRIPTION
    The stamp is the file's own LastWriteTime floored to the minute, so it records when the file was
    last edited. After writing it the script restores that LastWriteTime, which makes the next run a
    no-op until somebody edits the file again: a stamp older than the file's mtime means "edited since".
    Nothing else is stored anywhere.

    Markdown gets <sub class="doc-stamp">..</sub> after the front matter and any leading HTML
    comment; HTML gets a small <div class="doc-stamp"> straight after <body>. An existing stamp has
    its 14 date bytes overwritten in place, so a large append-only log is never rewritten whole.
    HTML without a <body> (an include fragment) and files outside the documentation scope are skipped
    and counted.

    Scope: docs/, documentation/, dev/ (not dev/archive or dev/CATALOG), the root pages, store_assets/,
    maestro/, delivery/, play/, meta/, inttent/, app_v2/ Markdown and scripts/ Markdown. Never
    stamped: PLAN/ (the catalog rewrites those headers), temp/, the read-only trees, .claude/, .venv,
    and the agent-rule files (CLAUDE.md, AGENTS.md, GEMINI.md, .github/) that every prompt re-reads.

.PARAMETER Files
    Repo-relative or absolute paths to consider. Out-of-scope paths are skipped.

.PARAMETER All
    Consider every document in scope.

.PARAMETER Check
    Write nothing; list files that lack a stamp or carry a stale one.

.PARAMETER IncludeGenerated
    Also stamp files that a generator writes (header marker, documentation/ pages, translated landing
    pages). Off by default: a generator rewrites its output, and a stamp it does not know about makes
    its -Check report drift. Turn it on only for generators that already ignore the stamp.

.PARAMETER Now
    Stamp with the current time instead of the file's mtime (the file's mtime is set to now as well).

.PARAMETER Quiet
    Print only the summary line.

.EXAMPLE
    pwsh -NoProfile -File scripts/docs/stamp-doc-dates.ps1 -All
    pwsh -NoProfile -File scripts/docs/stamp-doc-dates.ps1 -Files "docs/FAQ.md,docs/FAQ-ru.md"
    pwsh -NoProfile -File scripts/docs/stamp-doc-dates.ps1 -All -Check

.NOTES
    Exit codes:
      0  every considered document is stamped and current (or was stamped now)
      1  -Check found a missing or stale stamp
      2  no input given, or a file could not be read or written
#>
[CmdletBinding()]
param(
    [string[]]$Files,
    [switch]$All,
    [switch]$Check,
    [switch]$Now,
    [switch]$IncludeGenerated,
    [switch]$Quiet
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
. (Join-Path $PSScriptRoot 'lib\doc-stamp.ps1')

$includeRoots = @('docs', 'documentation', 'dev', 'store_assets', 'maestro', 'delivery', 'play', 'meta',
    'inttent', 'app_v2', 'scripts')
# Lower-case, forward-slash prefixes and exact names that are never stamped.
$excludePrefixes = @(
    'plan/', 'temp/', 'v1/', 'v2_6/', 'spec_v2/', 'dev/archive/', 'dev/catalog/', '.claude/', '.agents/',
    '.git/', '.github/', '.venv/', '.idea/', '.gradle/', 'build/', 'node_modules/', '_includes/'
)
$excludeNames = @('claude.md', 'agents.md', 'gemini.md')
$skipSegments = @('/node_modules/', '/build/', '/.venv/', '/__pycache__/', '/.gradle/')

# dev/CHANGELOG.md announces itself as auto-generated but is an append-only log that no generator
# re-renders, so it is stamped; its date is patched in place and the file is never rewritten whole.
$appendOnlyLogs = @('dev/changelog.md')
# index-ru/index-uk are hand-maintained translations; every other index-<slug>.html is written by
# scripts/site/generate-landing-pages.ps1 from index.html and carries index.html's own stamp.
$generatedPathPatterns = @('^documentation/.+\.html$', '^index-(?!ru\.html$|uk\.html$)[a-z-]+\.html$')
# A generator's own header: an HTML comment naming it, or a line that opens with "Generated by/from".
# A sentence that merely mentions generation ("..., which is generated from the build") is hand-written.
$generatedMarker = [regex]::new('(?im)^\s*(?:<!--.*?(?:GENERATED|do not (?:hand-)?edit)|>?\s*(?:auto-)?generated (?:by|from)\b)')

function Test-GeneratedFile([string]$Rel, [string]$Text) {
    $low = $Rel.ToLowerInvariant()
    if ($appendOnlyLogs -contains $low) { return $false }
    foreach ($pattern in $generatedPathPatterns) { if ($low -match $pattern) { return $true } }
    $head = if ($Text.Length -gt 1500) { $Text.Substring(0, 1500) } else { $Text }
    return $generatedMarker.IsMatch($head)
}

function Get-RelativePath([string]$FullPath) {
    return $FullPath.Substring($repoRoot.Length).TrimStart('\', '/').Replace('\', '/')
}

function Test-InScope([string]$Rel) {
    $kind = Get-DocStampKind -Path $Rel
    if (-not $kind) { return $false }
    $low = $Rel.ToLowerInvariant()
    foreach ($p in $excludePrefixes) { if ($low.StartsWith($p)) { return $false } }
    if ($excludeNames -contains $low) { return $false }
    foreach ($s in $skipSegments) { if (("/$low").Contains($s)) { return $false } }
    if (-not $low.Contains('/')) { return $true }
    return ($includeRoots -contains $low.Split('/')[0])
}

function Get-ScopeFiles {
    $found = [System.Collections.Generic.List[string]]::new()
    foreach ($f in (Get-ChildItem -Path (Join-Path $repoRoot *) -File -Include '*.md', '*.html', '*.htm' -ErrorAction SilentlyContinue)) {
        $found.Add($f.FullName)
    }
    foreach ($root in $includeRoots) {
        $dir = Join-Path $repoRoot $root
        if (-not (Test-Path -LiteralPath $dir)) { continue }
        foreach ($f in (Get-ChildItem -LiteralPath $dir -Recurse -File -Include '*.md', '*.html', '*.htm' -ErrorAction SilentlyContinue)) {
            $found.Add($f.FullName)
        }
    }
    return $found
}

$candidates = [System.Collections.Generic.List[string]]::new()
if ($All) {
    foreach ($p in (Get-ScopeFiles)) { $candidates.Add($p) }
}
foreach ($entry in @($Files)) {
    foreach ($piece in ($entry -split ',')) {
        $piece = $piece.Trim()
        if (-not $piece) { continue }
        $full = if ([IO.Path]::IsPathRooted($piece)) { $piece } else { Join-Path $repoRoot $piece }
        $candidates.Add($full)
    }
}
if ($candidates.Count -eq 0) {
    Write-Host 'stamp-doc-dates: nothing to do - pass -All or -Files' -ForegroundColor Yellow
    exit 2
}

$stamped = 0; $refreshed = 0; $current = 0; $skippedScope = 0; $skippedFragment = 0; $skippedGenerated = 0; $problems = 0
$pending = [System.Collections.Generic.List[string]]::new()
$nowDate = Get-Date

foreach ($path in ($candidates | Select-Object -Unique)) {
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) { $skippedScope++; continue }
    $rel = Get-RelativePath $path
    if (-not (Test-InScope $rel)) { $skippedScope++; continue }
    try {
        $kind = Get-DocStampKind -Path $rel
        $mtime = (Get-Item -LiteralPath $path).LastWriteTime
        $when = if ($Now) { $nowDate } else { $mtime }
        $floored = $when.Date.AddHours($when.Hour).AddMinutes($when.Minute)
        $dateText = Format-DocStampDate -When $floored

        $doc = Read-DocFile -Path $path
        if ($doc.Text.Length -eq 0) { $skippedFragment++; continue }
        if (-not $IncludeGenerated -and (Test-GeneratedFile -Rel $rel -Text $doc.Text)) { $skippedGenerated++; continue }
        $existing = Get-DocStampValue -Text $doc.Text
        $isStale = $false
        if ($null -ne $existing) {
            $isStale = (ConvertFrom-DocStampDate -Text $existing) -lt $floored
            if (-not $isStale) { $current++; continue }
        }

        if ($Check) { $pending.Add($rel + $(if ($null -eq $existing) { '  [missing]' } else { "  [stale: $existing < $dateText]" })); continue }

        $keep = if ($Now) { $nowDate } else { $mtime }
        if ($null -ne $existing) {
            if (Update-DocStampInPlace -Path $path -Date $dateText -KeepTime $keep) { $refreshed++; continue }
        }
        $newText = Add-DocStamp -Text $doc.Text -Kind $kind -Date $dateText
        if ($null -eq $newText) { $skippedFragment++; continue }
        Write-DocFile -Path $path -Text $newText -HasBom $doc.HasBom -KeepTime $keep
        if ($null -ne $existing) { $refreshed++ } else { $stamped++ }
    } catch {
        $problems++
        Write-Host "stamp-doc-dates: $rel - $($_.Exception.Message)" -ForegroundColor Red
    }
}

if ($Check) {
    if (-not $Quiet) { $pending | ForEach-Object { Write-Host "  $_" } }
    Write-Host "stamp-doc-dates -Check: $($pending.Count) need a stamp, $current current, $skippedGenerated generated skipped, $skippedScope out of scope" -ForegroundColor $(if ($pending.Count) { 'Red' } else { 'Green' })
    if ($problems) { exit 2 }
    exit $(if ($pending.Count) { 1 } else { 0 })
}

Write-Host "stamp-doc-dates: stamped $stamped, refreshed $refreshed, already current $current, fragments skipped $skippedFragment, generated skipped $skippedGenerated, out of scope $skippedScope, errors $problems" -ForegroundColor $(if ($problems) { 'Red' } else { 'Green' })
exit $(if ($problems) { 2 } else { 0 })
