#requires -Version 7.0
<#
.SYNOPSIS
    S2125: fails when a string mirrored on the phone and the watch stops reading the same.

.DESCRIPTION
    :app_v2 and :wear compile separately with no shared resource artifact, so every label the owner
    sees on both sides physically exists twice - one key per module. S2093 introduced
    assert-wear-settings-parity.ps1, which checks that a watch setting EXISTS on both sides, but it
    never reads the text of the label. Editing one copy therefore left no trace on the other, and the
    divergence surfaced only on a live phone-plus-watch pair.

    The pairing is declared in wear-mirrored-strings.psd1 beside this script, never inferred from a
    matching key name. Measured 2026-08-27: 20 key names occur in both modules, 6 already differ in
    `en` and 8 more diverge in 12 places across bn/pt/ru/uk, several of them deliberately - the watch
    picks the shorter word where the round screen demands it.

    Checks:
      1. A Mirrored pair reads identically in every locale both sides declare it in.
      2. A Mirrored pair is declared by both sides in the same set of locales.
      3. An Independent record carries a non-empty Reason.
      4. A key name present in both modules' values/strings.xml is classified by the declaration.
         Without this the list ages in silence, which is the disease the ticket treats.

    Check 4 is what keeps the declaration honest: a new colliding key must be called Mirrored or
    Independent by the author who added it, because that intent cannot be recovered later.

    Rule 33 class: SPLIT BY SUBJECT across two scopes (S2562), because the thirteen locales do not
    all have the same author. Three are written by hand in the same edit as the surface (Rule 30);
    the other ten are filled by a batch translation at the release boundary (S1627), and app_v2 and
    wear make that trip SEPARATELY - every script in the chain declares `$Module = 'app_v2'` and the
    watch is covered by its own `-Module wear` call. No glossary and no translation memory exist in
    that chain, and the translated unit is identified module-qualified (`module|set|file|key`), so
    nothing reuses one module's translation for the other. Two independent machine translations of
    one English phrase are therefore not expected to agree, and their divergence is regenerated by
    every release's batch import - it is the normal state between releases, not accumulated debt.
    That is why this gate carries no baseline ratchet: a ratchet records accepted debt, and a
    baseline over a set that is rewritten each release would be stale by construction.

      -Scope Authored - checks 3 and 4 in full, and checks 1 and 2 over the AUTHORED locales only.
                        Everything here is the change author's own work and is fatal per ticket:
                        author intent cannot be recovered later, which is Rule 33's counter-condition
                        for staying per-ticket. This is what post-change.ps1 passes.
      -Scope All      - the same, plus checks 1 and 2 over all thirteen locales. Runs at the release
                        boundary from assert-prerelease-content-gates.ps1, where the batch import has
                        happened and the owner can reconcile the wording.

    Measured 2026-09-05 (S2562), the split is not cosmetic: the gate reported 34 findings, of which
    25 were text divergences living exclusively in the ten batch-translated locales and none at all
    in values/values-ru/values-uk. Judged per ticket, that set refused the closure of S2392 - a
    ticket that added one key in the three authored locales and appeared in none of the findings.

    The authored set is READ from scripts/utils/locale-set.ps1 (Get-StrictLocales), never restated
    here: that file is already the one home of the strict subset, and a second copy would drift from
    it silently. Only Get-StrictLocales and Get-LocaleResourceDir are used, neither of which reads
    locales_config.xml, so dot-sourcing it cannot trigger its exit 3.

.PARAMETER Gate
    Exit 1 on a divergence instead of reporting it advisorily.

.PARAMETER Quiet
    Suppress the PASS line. Findings and the failure verdict are still printed.

.PARAMETER Scope
    Which locales checks 1 and 2 compare. 'Authored' judges only the owner-written locales,
    'All' judges every discovered locale. Default 'All' - a caller narrows deliberately, so a bare
    run reports everything. Checks 3 and 4 are locale-free and run under both.

.NOTES
    Exit codes:
      0 - every declared pair is in step; or a divergence was reported without -Gate, matching the
          advisory shape of the sibling gates in assert-fast-gates.ps1.
      1 - a divergence was found and -Gate was passed.
      2 - could not verify: the declaration is missing, parses to zero pairs, or a strings.xml under
          a discovered locale could not be read as XML. A caller must tell this from 1 - "found a
          defect" and "did not look" are different answers.
#>
[CmdletBinding()]
param(
    [switch]$Gate,
    [switch]$Quiet,
    [ValidateSet('Authored', 'All')]
    [string]$Scope = 'All'
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)

$declarationPath = Join-Path $PSScriptRoot 'wear-mirrored-strings.psd1'
$phoneResRoot = Join-Path $root 'app_v2/src/main/res'
$watchResRoot = Join-Path $root 'wear/src/main/res'

foreach ($required in @($declarationPath, $phoneResRoot, $watchResRoot)) {
    if (-not (Test-Path -LiteralPath $required)) {
        Write-Error "assert-wear-mirrored-strings: could not verify - missing $required" -ErrorAction Continue
        exit 2
    }
}

try {
    $declaration = Import-PowerShellDataFile -LiteralPath $declarationPath
}
catch {
    Write-Error "assert-wear-mirrored-strings: could not verify - declaration unreadable: $($_.Exception.Message)" -ErrorAction Continue
    exit 2
}

if (-not $declaration.Contains('Pairs') -or @($declaration.Pairs).Count -eq 0) {
    Write-Error 'assert-wear-mirrored-strings: could not verify - declaration parsed to zero pairs.' -ErrorAction Continue
    exit 2
}
$pairs = @($declaration.Pairs)

# Read one strings.xml into name -> text. InnerXml rather than InnerText, so an entity or an inline
# tag that differs between the two sides is a difference rather than being normalised away.
function Read-StringTable {
    param([string]$Path)

    $table = @{}
    if (-not (Test-Path -LiteralPath $Path)) { return $table }

    try {
        $xml = [xml](Get-Content -LiteralPath $Path -Raw)
    }
    catch {
        Write-Error "assert-wear-mirrored-strings: could not verify - $Path is not readable XML: $($_.Exception.Message)" -ErrorAction Continue
        exit 2
    }

    if ($null -eq $xml.resources) { return $table }
    foreach ($node in $xml.resources.string) {
        if ($null -ne $node -and $node.name) { $table[$node.name] = $node.InnerXml }
    }
    return $table
}

# The locale set is discovered from the tree rather than pinned, so a fourteenth locale is picked up
# without editing this gate. Only a folder carrying strings.xml on at least one side is considered.
#
# The whole pipeline is wrapped in @(), not just its first stage: Sort-Object -Unique returns a bare
# string when exactly one directory survives the filter, and `.Count` on a string is a terminating
# error under the Set-StrictMode -Version Latest above - the gate would die with exit 1, reporting a
# divergence it never looked for. Thirteen locales ship today so the real tree never reached it, and
# it stayed invisible until S2562's suite built a one-locale fixture.
$localeNames = @(
    @(
        @(Get-ChildItem -LiteralPath $phoneResRoot -Directory -Filter 'values*') +
        @(Get-ChildItem -LiteralPath $watchResRoot -Directory -Filter 'values*')
    ) |
        Where-Object {
            (Test-Path -LiteralPath (Join-Path $phoneResRoot "$($_.Name)/strings.xml")) -or
            (Test-Path -LiteralPath (Join-Path $watchResRoot "$($_.Name)/strings.xml"))
        } |
        ForEach-Object { $_.Name } |
        Sort-Object -Unique
)

if ($localeNames.Count -eq 0) {
    Write-Error 'assert-wear-mirrored-strings: could not verify - no values*/strings.xml found in either module.' -ErrorAction Continue
    exit 2
}

# S2562. Which locales checks 1 and 2 compare. The authored tags come from locale-set.ps1 rather
# than a literal here, so adding a fourteenth authored language stays a one-line edit in that file.
$comparedLocales = $localeNames
if ($Scope -eq 'Authored') {
    . (Join-Path $root 'scripts/utils/locale-set.ps1')
    $authoredDirs = @(Get-StrictLocales | ForEach-Object { Get-LocaleResourceDir -Tag $_ })
    $comparedLocales = @($localeNames | Where-Object { $authoredDirs -contains $_ })

    if ($comparedLocales.Count -eq 0) {
        Write-Error ('assert-wear-mirrored-strings: could not verify - -Scope Authored selected no locale. ' +
            'Expected one of: ' + ($authoredDirs -join ', ') + '. A run that compares nothing must not report PASS.') -ErrorAction Continue
        exit 2
    }
}

# Only the compared locales are read. Under -Scope Authored that also keeps a malformed strings.xml
# in a batch-translated locale from failing a per-ticket closure with exit 2 over a file outside the
# scope this run declared. `values` is read regardless, because check 4 sweeps the default locale.
$localesToRead = @($comparedLocales)
if ($localeNames -contains 'values' -and $localesToRead -notcontains 'values') {
    $localesToRead += 'values'
}

$phoneByLocale = [ordered]@{}
$watchByLocale = [ordered]@{}
foreach ($locale in $localesToRead) {
    $phoneByLocale[$locale] = Read-StringTable (Join-Path $phoneResRoot "$locale/strings.xml")
    $watchByLocale[$locale] = Read-StringTable (Join-Path $watchResRoot "$locale/strings.xml")
}

$findings = @()
$comparisons = 0
$mirroredCount = 0

foreach ($pair in $pairs) {
    $phoneKey = [string]$pair.Phone
    $watchKey = [string]$pair.Watch
    $mode = [string]$pair.Mode
    $reason = if ($pair.Contains('Reason')) { [string]$pair.Reason } else { '' }
    $label = if ($phoneKey -eq $watchKey) { $phoneKey } else { "$phoneKey / $watchKey" }

    if ($mode -eq 'Independent') {
        # 3. An exception without a recorded reason is indistinguishable from a forgotten string -
        #    the same rule the S2093 registry applies to a one-sided setting.
        if ([string]::IsNullOrWhiteSpace($reason)) {
            $findings += "S2125: '$label' is Independent with no Reason - record why the two sides word it differently, or make it Mirrored."
        }
        continue
    }

    if ($mode -ne 'Mirrored') {
        $findings += "S2125: '$label' declares Mode '$mode' - only 'Mirrored' and 'Independent' exist."
        continue
    }

    $mirroredCount++

    foreach ($locale in $comparedLocales) {
        $hasPhone = $phoneByLocale[$locale].ContainsKey($phoneKey)
        $hasWatch = $watchByLocale[$locale].ContainsKey($watchKey)

        if ($hasPhone -and $hasWatch) {
            # 1. The pair must read the same.
            $comparisons++
            if ($phoneByLocale[$locale][$phoneKey] -ne $watchByLocale[$locale][$watchKey]) {
                $findings += ("S2125: '$label' differs in $locale - phone '" +
                    $phoneByLocale[$locale][$phoneKey] + "' vs watch '" +
                    $watchByLocale[$locale][$watchKey] + "'.")
            }
        }
        elseif ($hasPhone -or $hasWatch) {
            # 2. A mirrored pair translated on one side only is the divergence arriving early.
            $missingSide = if ($hasPhone) { 'watch' } else { 'phone' }
            $presentSide = if ($hasPhone) { 'phone' } else { 'watch' }
            $findings += "S2125: '$label' is declared in $locale on the $presentSide side only - the $missingSide side has no such key."
        }
    }
}

# 4. Completeness, judged from the other direction: a key name both modules declare and this file
#    classifies neither way. Only the default locale is swept - a key reaches a translation because
#    it exists in `values` first, so that is where a new collision appears.
$declaredPhoneKeys = @($pairs | ForEach-Object { [string]$_.Phone })
$declaredWatchKeys = @($pairs | ForEach-Object { [string]$_.Watch })
$phoneDefault = if ($phoneByLocale.Contains('values')) { $phoneByLocale['values'] } else { @{} }
$watchDefault = if ($watchByLocale.Contains('values')) { $watchByLocale['values'] } else { @{} }

foreach ($key in ($phoneDefault.Keys | Sort-Object)) {
    if (-not $watchDefault.ContainsKey($key)) { continue }
    if ($key -in $declaredPhoneKeys -and $key -in $declaredWatchKeys) { continue }
    $findings += ("S2125: '$key' exists in both modules but wear-mirrored-strings.psd1 classifies it " +
        "neither Mirrored nor Independent - declare which it is.")
}

# The scope is named in BOTH verdicts, never only in the failure. A PASS that compared three locales
# and a PASS that compared thirteen are different claims, and a reader who cannot tell them apart
# would take the narrow one for full coverage (S2562).
$scopeLabel = "-Scope $Scope over $($comparedLocales.Count) locale(s): $($comparedLocales -join ', ')"

if ($findings.Count -eq 0) {
    if (-not $Quiet) {
        Write-Host ("assert-wear-mirrored-strings: PASS - $mirroredCount mirrored pair(s), " +
            "$comparisons text comparison(s), $scopeLabel, no divergence.")
    }
    exit 0
}

Write-Error ("assert-wear-mirrored-strings: FAIL - " + $findings.Count + " divergence(s) [$scopeLabel]:`n" +
    (($findings | Sort-Object -Unique) -join "`n")) -ErrorAction Continue
if ($Gate) { exit 1 }
exit 0
