#requires -Version 7.0
<#
.SYNOPSIS
    Generate canonical toolchain version pins from the build configuration.

.DESCRIPTION
    Reads SDK levels and key dependency versions directly from the Gradle build
    files (the single source of truth - there is no version catalog) and renders
    a normalized pin list. Canonical documents carry this list inside a delimited
    managed block so doc-vs-build drift becomes structurally impossible.

    Every version is READ from the build files; no version literal is embedded in
    this script.

    Exit codes (S1070):
      0 - clean (pins in sync, or a successful -Write).
      1 - substantive failure: doc-vs-build pin drift under -Check.
      2 - the tool itself cannot run: a build file or target document is missing,
          a version could not be read, or the managed-block markers are absent.
          Distinct from 1 on purpose - "cannot check" is not "drift found".

    Modes:
      (default)  Print the generated managed block to stdout.
      -Write     Replace the managed block in each target document in place.
      -Check     Regenerate and compare against each target's managed block;
                 exit 1 on any drift or missing block (fail-closed gate).

.EXAMPLE
    pwsh -NoProfile -File scripts/quality/generate-toolchain-pins.ps1
    pwsh -NoProfile -File scripts/quality/generate-toolchain-pins.ps1 -Write
    pwsh -NoProfile -File scripts/quality/generate-toolchain-pins.ps1 -Check
#>
[CmdletBinding(DefaultParameterSetName = 'Print')]
param(
    [Parameter(ParameterSetName = 'Write')][switch]$Write,
    [Parameter(ParameterSetName = 'Check')][switch]$Check
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$appGradle = Join-Path $repoRoot 'app_v2/build.gradle.kts'
$rootGradle = Join-Path $repoRoot 'build.gradle.kts'

$startMarker = '<!-- toolchain-pins:start (generated by scripts/quality/generate-toolchain-pins.ps1 - do not edit by hand) -->'
$endMarker = '<!-- toolchain-pins:end -->'

# Documents that carry the managed block.
$targets = @(
    (Join-Path $repoRoot 'CLAUDE.md'),
    (Join-Path $repoRoot 'docs/TECH_STACK.md')
)

function Get-Capture([string]$text, [string]$pattern) {
    $m = [regex]::Match($text, $pattern)
    if (-not $m.Success) { return $null }
    return $m.Groups[1].Value
}

function Get-AllCaptures([string]$text, [string]$pattern) {
    [regex]::Matches($text, $pattern) | ForEach-Object { $_.Groups[1].Value }
}

if (-not (Test-Path $appGradle)) { Write-Error "Not found: $appGradle" -ErrorAction Continue; exit 2 }

$app = Get-Content -LiteralPath $appGradle -Raw
$rootText = if (Test-Path $rootGradle) { Get-Content -LiteralPath $rootGradle -Raw } else { '' }

# Build the digit-class fragment without an embedded version literal.
$d = '[0-9]'
$ver = "($d$d*(?:\.$d+)*)"

$compileSdk = Get-Capture $app ('compileSdk\s*=\s*(' + $d + '+)')
$targetSdk = Get-Capture $app ('targetSdk\s*=\s*(' + $d + '+)')
$minSdkAll = @(Get-AllCaptures $app ('minSdk\s*=\s*(' + $d + '+)'))
$minStandard = if ($minSdkAll.Count -gt 0) { $minSdkAll[0] } else { $null }
$minLegacy = if ($minSdkAll.Count -gt 1) { ($minSdkAll | Sort-Object { [int]$_ })[0] } else { $minStandard }

$kotlin = Get-Capture $rootText ('org\.jetbrains\.kotlin[^"]*"\)?\s*version\s*"' + $ver)
$room = Get-Capture $app ('androidx\.room:room-runtime:' + $ver)
$media3 = Get-Capture $app ('androidx\.media3:media3-exoplayer:' + $ver)
$glide = Get-Capture $app ('com\.github\.bumptech\.glide:glide:' + $ver)

$pins = [ordered]@{
    'compileSdk'         = $compileSdk
    'targetSdk'          = $targetSdk
    'minSdk (standard)'  = $minStandard
    'minSdk (legacy)'    = $minLegacy
    'Kotlin'             = $kotlin
    'Room'               = $room
    'Media3 (ExoPlayer)' = $media3
    'Glide'              = $glide
}

$missing = $pins.GetEnumerator() | Where-Object { [string]::IsNullOrWhiteSpace($_.Value) }
if ($missing) {
    Write-Error ("Could not read from build files: " + (($missing | ForEach-Object { $_.Key }) -join ', ')) -ErrorAction Continue
    exit 2
}

$bodyLines = $pins.GetEnumerator() | ForEach-Object { "- {0}: {1}" -f $_.Key, $_.Value }
$block = ($startMarker, '') + $bodyLines + ('', $endMarker) -join "`n"

function Get-ExistingBlock([string]$docText) {
    $rx = [regex]::Escape($startMarker) + '.*?' + [regex]::Escape($endMarker)
    $m = [regex]::Match($docText, $rx, [System.Text.RegularExpressions.RegexOptions]::Singleline)
    if ($m.Success) { return $m.Value } else { return $null }
}

switch ($PSCmdlet.ParameterSetName) {
    'Check' {
        $drift = 0
        foreach ($t in $targets) {
            if (-not (Test-Path $t)) { Write-Host "MISSING doc: $t"; $drift++; continue }
            $docText = Get-Content -LiteralPath $t -Raw
            $existing = Get-ExistingBlock $docText
            $rel = (Split-Path $t -Leaf)
            if ($null -eq $existing) { Write-Host "MISSING managed block in $rel"; $drift++; continue }
            if ($existing.Replace("`r`n", "`n").Trim() -ne $block.Trim()) {
                Write-Host "DRIFT in $rel (managed block != generated pins)"; $drift++
            }
            else { Write-Host "OK $rel" }
        }
        Write-Host ("generate-toolchain-pins -Check: expected drift 0 | actual {0}" -f $drift)
        if ($drift -gt 0) { exit 1 }
        exit 0
    }
    'Write' {
        $rx = [regex]::Escape($startMarker) + '.*?' + [regex]::Escape($endMarker)
        foreach ($t in $targets) {
            if (-not (Test-Path $t)) { Write-Error "Target not found: $t" -ErrorAction Continue; exit 2 }
            $docText = Get-Content -LiteralPath $t -Raw
            if (-not [regex]::IsMatch($docText, $rx, [System.Text.RegularExpressions.RegexOptions]::Singleline)) {
                Write-Error "Managed block markers missing in $(Split-Path $t -Leaf). Add the marker pair first, then re-run -Write." -ErrorAction Continue
                exit 2
            }
            $eol = if ($docText.Contains("`r`n")) { "`r`n" } else { "`n" }
            $blockEol = $block.Replace("`n", $eol)
            # MatchEvaluator returns the block literally - avoids $-substitution in the replacement.
            $evaluator = [System.Text.RegularExpressions.MatchEvaluator] { param($m) $blockEol }
            $re = [regex]::new($rx, [System.Text.RegularExpressions.RegexOptions]::Singleline)
            $updated = $re.Replace($docText, $evaluator)
            [System.IO.File]::WriteAllText($t, $updated)
            Write-Host "Wrote managed block -> $(Split-Path $t -Leaf)"
        }
        exit 0
    }
    default {
        Write-Output $block
        exit 0
    }
}
