#requires -Version 7.0
<#
.SYNOPSIS
    Measures reproducible project statistics and records a dated history snapshot.

.DESCRIPTION
    Counts tracked repository files so generated build output and local scratch data never affect
    a measurement. Code-line metrics are non-empty Kotlin/Java source lines for Phone and Wear,
    plus non-empty PowerShell lines for automation. Text assets are counted separately.

.PARAMETER NoRecord
    Prints the current measurement without changing the JSONL history or Markdown report.

.PARAMETER RepoRoot
    Repository root. Defaults to the directory two levels above this script.

.NOTES
    Exit codes:
      0 - measurement completed; history and report were written unless -NoRecord was used
      1 - measurement could not be completed
#>
[CmdletBinding()]
param(
    [switch] $NoRecord,
    [string] $RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Get-NonEmptyLineCount {
    param([string[]] $Paths)

    $count = 0
    foreach ($relativePath in $Paths) {
        $fullPath = Join-Path $RepoRoot ($relativePath -replace '/', [IO.Path]::DirectorySeparatorChar)
        if (-not (Test-Path -LiteralPath $fullPath -PathType Leaf)) { continue }
        foreach ($line in [IO.File]::ReadAllLines($fullPath)) {
            if (-not [string]::IsNullOrWhiteSpace($line)) { $count++ }
        }
    }
    return $count
}

function Get-UniqueDependencyCount {
    $coordinates = [System.Collections.Generic.HashSet[string]]::new([StringComparer]::OrdinalIgnoreCase)
    $catalogPath = Join-Path $RepoRoot 'gradle/libs.versions.toml'
    if (Test-Path -LiteralPath $catalogPath) {
        $inLibraries = $false
        foreach ($line in [IO.File]::ReadAllLines($catalogPath)) {
            if ($line -match '^\s*\[([^]]+)\]') {
                $inLibraries = $Matches[1] -eq 'libraries'
                continue
            }
            if (-not $inLibraries) { continue }
            $moduleMatch = [regex]::Match($line, 'module\s*=\s*"([^"]+:[^"]+)"')
            if ($moduleMatch.Success) {
                [void]$coordinates.Add($moduleMatch.Groups[1].Value)
                continue
            }
            $shortMatch = [regex]::Match($line, '=\s*"([^":]+:[^":]+):[^"]+"')
            if ($shortMatch.Success) { [void]$coordinates.Add($shortMatch.Groups[1].Value) }
        }
    }

    foreach ($buildFile in Get-ChildItem -LiteralPath $RepoRoot -Filter '*.gradle.kts' -Recurse -File) {
        foreach ($match in [regex]::Matches([IO.File]::ReadAllText($buildFile.FullName),
                '(?m)\b(?:implementation|api|compileOnly|runtimeOnly|kapt|ksp|testImplementation|androidTestImplementation|debugImplementation|releaseImplementation)\s*\(\s*"([^":]+:[^":]+):[^"]+"')) {
            [void]$coordinates.Add($match.Groups[1].Value)
        }
    }
    return $coordinates.Count
}

function Get-ReportText {
    param([pscustomobject] $Current, [object[]] $History)

    $metricRows = [ordered]@{
        'Total code lines' = $Current.total_code_lines
        'Phone code lines' = $Current.phone_code_lines
        'Wear code lines' = $Current.wear_code_lines
        'Script code lines' = $Current.script_code_lines
        'Text asset lines' = $Current.asset_text_lines
        'Project files' = $Current.tracked_files
        'Gradle modules' = $Current.gradle_modules
        'Images' = $Current.images
        'Third-party libraries' = $Current.third_party_libraries
        'Kotlin/Java source files' = $Current.source_files
        'Test source files' = $Current.test_source_files
        'Asset files' = $Current.asset_files
        'Source files over 500 lines' = $Current.source_files_over_500_lines
        'Source files over 2000 lines' = $Current.source_files_over_2000_lines
        'TODO/FIXME markers' = $Current.todo_fixme_markers
    }
    $snapshotLines = foreach ($name in $metricRows.Keys) { "| $name | $($metricRows[$name]) |" }
    $historyLines = foreach ($entry in $History) {
        $measuredAt = ([DateTime]$entry.measured_at).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')
        "| $measuredAt | $($entry.total_code_lines) | $($entry.phone_code_lines) | $($entry.wear_code_lines) | $($entry.script_code_lines) | $($entry.asset_text_lines) | $($entry.tracked_files) | $($entry.images) | $($entry.third_party_libraries) |"
    }

    return (@(
        '# Project Statistics',
        '',
        '> Generated by `scripts/quality/measure-project-statistics.ps1`. Do not edit values or history by hand.',
        '',
        '## Current snapshot',
        '',
        ('Measurement: `{0}` (commit `{1}`, branch `{2}`).' -f $Current.measured_at, $Current.commit, $Current.branch),
        '',
        '| Metric | Value |',
        '| --- | ---: |',
        ($snapshotLines -join [Environment]::NewLine),
        '',
        '## Measurement scope',
        '',
        '- The population is version-controlled and nonignored working-tree files, excluding generated build output and `temp/` artifacts.',
        '- Phone and Wear code lines are non-empty `.kt` and `.java` source lines under each module `src/` tree.',
        '- Script code lines are non-empty `.ps1` and `.psm1` lines under `scripts/`.',
        '- Text asset lines are non-empty lines in files below an `assets/` directory with text-oriented extensions.',
        '- Third-party libraries are unique `group:artifact` coordinates from the Gradle version catalog and direct Gradle dependency declarations.',
        '- Image count uses tracked files with png, jpg, jpeg, webp, gif, bmp, svg, avif, or heic extensions.',
        '',
        '## History',
        '',
        '| Measured (UTC) | Total code | Phone | Wear | Scripts | Text assets | Files | Images | Libraries |',
        '| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |',
        ($historyLines -join [Environment]::NewLine),
        ''
    ) -join [Environment]::NewLine)
}

try {
    $RepoRoot = (Resolve-Path -LiteralPath $RepoRoot).Path
    $tracked = @(& git -C $RepoRoot ls-files --cached --others --exclude-standard)
    if ($LASTEXITCODE -ne 0 -or $tracked.Count -eq 0) { throw 'git ls-files returned no project files.' }
    $projectFiles = @($tracked | Where-Object {
        Test-Path -LiteralPath (Join-Path $RepoRoot ($_ -replace '/', [IO.Path]::DirectorySeparatorChar)) -PathType Leaf
    })

    $sourcePaths = @($projectFiles | Where-Object { $_ -match '^(app_v2|wear)/src/.+\.(kt|java)$' })
    $phoneSourcePaths = @($sourcePaths | Where-Object { $_ -match '^app_v2/' })
    $wearSourcePaths = @($sourcePaths | Where-Object { $_ -match '^wear/' })
    $scriptPaths = @($projectFiles | Where-Object { $_ -match '^scripts/.+\.(ps1|psm1)$' })
    $assetExtensions = '\.(json|csv|txt|xml|html|htm|js|css|svg|md|properties)$'
    $assetPaths = @($projectFiles | Where-Object { $_ -match '(^|/)assets/' })
    $textAssetPaths = @($assetPaths | Where-Object { $_ -match $assetExtensions })
    $imagePaths = @($projectFiles | Where-Object { $_ -match '\.(png|jpe?g|webp|gif|bmp|svg|avif|heic)$' })
    $testSourcePaths = @($sourcePaths | Where-Object { $_ -match '/src/(?:test|androidTest|test[A-Za-z0-9_-]+)/' })

    $sourceLineCounts = @{}
    foreach ($sourcePath in $sourcePaths) { $sourceLineCounts[$sourcePath] = Get-NonEmptyLineCount @($sourcePath) }
    $todoFixmeMarkers = 0
    foreach ($sourcePath in $sourcePaths) {
        $fullPath = Join-Path $RepoRoot ($sourcePath -replace '/', [IO.Path]::DirectorySeparatorChar)
        $todoFixmeMarkers += [regex]::Matches([IO.File]::ReadAllText($fullPath), '(?i)\b(?:TODO|FIXME)\b').Count
    }

    $settingsText = [IO.File]::ReadAllText((Join-Path $RepoRoot 'settings.gradle.kts'))
    $moduleCount = [regex]::Matches($settingsText, 'include\(\s*"(:[^"]+)"\s*\)').Count
    $now = [DateTime]::UtcNow
    $current = [pscustomobject][ordered]@{
        measured_at = $now.ToString('yyyy-MM-ddTHH:mm:ssZ')
        commit = (& git -C $RepoRoot rev-parse --short HEAD).Trim()
        branch = (& git -C $RepoRoot branch --show-current).Trim()
        total_code_lines = (Get-NonEmptyLineCount ($phoneSourcePaths + $wearSourcePaths + $scriptPaths))
        phone_code_lines = Get-NonEmptyLineCount $phoneSourcePaths
        wear_code_lines = Get-NonEmptyLineCount $wearSourcePaths
        script_code_lines = Get-NonEmptyLineCount $scriptPaths
        asset_text_lines = Get-NonEmptyLineCount $textAssetPaths
        tracked_files = $projectFiles.Count
        gradle_modules = $moduleCount
        images = $imagePaths.Count
        third_party_libraries = Get-UniqueDependencyCount
        source_files = $sourcePaths.Count
        test_source_files = $testSourcePaths.Count
        asset_files = $assetPaths.Count
        source_files_over_500_lines = @($sourceLineCounts.Values | Where-Object { $_ -gt 500 }).Count
        source_files_over_2000_lines = @($sourceLineCounts.Values | Where-Object { $_ -gt 2000 }).Count
        todo_fixme_markers = $todoFixmeMarkers
    }

    $current | ConvertTo-Json -Depth 3
    if ($NoRecord) { exit 0 }

    $statisticsDir = Join-Path $RepoRoot 'docs/project-statistics'
    $historyPath = Join-Path $statisticsDir 'history.jsonl'
    $reportPath = Join-Path $RepoRoot 'docs/PROJECT_STATISTICS.md'
    [IO.Directory]::CreateDirectory($statisticsDir) | Out-Null
    [IO.File]::AppendAllText($historyPath, (($current | ConvertTo-Json -Compress) + [Environment]::NewLine))
    $history = @([IO.File]::ReadAllLines($historyPath) |
        Where-Object { -not [string]::IsNullOrWhiteSpace($_) } |
        ForEach-Object { $_ | ConvertFrom-Json })
    [IO.File]::WriteAllText($reportPath, (Get-ReportText -Current $current -History $history) + [Environment]::NewLine)
    Write-Host "project-statistics: recorded $($current.measured_at) in docs/PROJECT_STATISTICS.md" -ForegroundColor Green
    exit 0
} catch {
    Write-Error "measure-project-statistics: $($_.Exception.Message)" -ErrorAction Continue
    exit 1
}
