<#
.SYNOPSIS
    Mandatory pre-release settings reindex - regenerate the settings search
    index mirror, then verify it is consistent with the app.

.DESCRIPTION
    The in-app settings search index is rebuilt at runtime on device by scanning
    the layouts in SettingsSearchLayoutCatalog and routing them through
    SettingsSearchTabMapping. Nothing is serialized into the APK, so what a build
    "ships" is only as current as three source-of-truth artifacts:
      - the layout catalog (a settings screen missing from it is invisible to search),
      - the tab mapping (a found row with no route cannot navigate to its setting),
      - the doc mirror (settings-manifest.json + SETTINGS_REFERENCE*.md + annotations
        + HOW_TO navigation paths).

    This wrapper makes the reindex an explicit, unconditional release step:
      1. REGENERATE docs/settings/settings-manifest.json from the live scan
         (SettingsManifestExportTest in generate mode).
      2. RE-RENDER docs/SETTINGS_REFERENCE*.md from the fresh manifest.
      3. VERIFY the whole chain with assert-settings-doc-sync.ps1
         (catalog-complete, annotations, reference-fresh, HOW_TO paths). The
         manifest-freshness stage is skipped here because step 1 just wrote it.

    A drift that regeneration silently fixed (steps 1-2 changed a committed file)
    is still a release finding: the fresh files MUST be committed so the build
    carries them. Issues regeneration cannot fix (a layout missing from the
    catalog, an unannotated key, a drifted HOW_TO path) fail the gate hard.

.PARAMETER DryRun
    List the planned actions and run nothing (no gradle, no writes). Used by the
    --dry-run path of /spec-prerelease.

.OUTPUTS
    Exit codes:
      0 - already fresh: nothing regenerated, verify gate green. Shippable.
      2 - drift regenerated: manifest/reference changed and are now fresh, but the
          new files must be committed before the release proceeds.
      3 - verify gate failed: an inconsistency regeneration cannot fix
          (catalog / annotations / HOW_TO). Hard release blocker.
      1 - infrastructure failure (gradle/render error, missing tool).
#>
param(
    [switch] $DryRun,
    [string] $RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
)

$ErrorActionPreference = 'Stop'
. (Join-Path $RepoRoot "scripts/utils/agent-lock.ps1")

# Files whose content is (re)generated by the reindex - a change here is drift.
$tracked = @(
    'docs/settings/settings-manifest.json',
    'docs/SETTINGS_REFERENCE.md',
    'docs/SETTINGS_REFERENCE_RU.md',
    'docs/SETTINGS_REFERENCE_UK.md',
    'docs/SETTINGS_REFERENCE_noLegal.md'
) | ForEach-Object { Join-Path $RepoRoot $_ }

function Get-Fingerprint {
    $sb = [System.Text.StringBuilder]::new()
    foreach ($f in $tracked) {
        if (Test-Path $f) {
            $h = (Get-FileHash -Algorithm SHA256 -LiteralPath $f).Hash
        } else {
            $h = 'MISSING'
        }
        [void]$sb.AppendLine("$h  $f")
    }
    $sb.ToString()
}

if ($DryRun) {
    Write-Host "reindex-settings [DRY-RUN] - would:" -ForegroundColor Cyan
    Write-Host "  1. regenerate docs/settings/settings-manifest.json (SettingsManifestExportTest -Dsettings.manifest.generate=true)"
    Write-Host "  2. re-render docs/SETTINGS_REFERENCE*.md"
    Write-Host "  3. verify with assert-settings-doc-sync.ps1 -SkipManifestTest"
    exit 0
}

$before = Get-Fingerprint

# Step 1 - regenerate the manifest from the live scan --------------------------
Enter-BuildLockOrExit -Reason "reindex-settings.ps1 (SettingsManifestExportTest generate)"
Push-Location $RepoRoot
try {
    & ".\gradlew.bat" ":app_v2:testStandardDebugUnitTest" "--tests" "*SettingsManifestExportTest" `
        "-Dsettings.manifest.generate=true" | Out-Null
    $genExit = $LASTEXITCODE
} finally { Pop-Location; Exit-AgentLock -Name Build }
if ($genExit -ne 0) {
    Write-Error "reindex-settings: manifest regeneration (gradle) failed" -ErrorAction Continue
    exit 1
}

# Step 2 - re-render the reference pages from the fresh manifest ----------------
& (Join-Path $RepoRoot 'scripts/docs/render-settings-reference.ps1') -RepoRoot $RepoRoot | Out-Null
if ($LASTEXITCODE -ne 0) {
    Write-Error "reindex-settings: SETTINGS_REFERENCE render failed" -ErrorAction Continue
    exit 1
}

# Step 3 - verify the whole chain (manifest freshness already guaranteed) -------
& (Join-Path $PSScriptRoot 'assert-settings-doc-sync.ps1') -SkipManifestTest -RepoRoot $RepoRoot
if ($LASTEXITCODE -ne 0) {
    Write-Error "reindex-settings: verify gate FAILED - an inconsistency regeneration cannot fix (catalog / annotations / HOW_TO). Hard release blocker." -ErrorAction Continue
    exit 3
}

$after = Get-Fingerprint
if ($before -ne $after) {
    Write-Error "reindex-settings: DRIFT regenerated - the settings index mirror was stale and has been refreshed. Commit the updated docs/settings/settings-manifest.json + docs/SETTINGS_REFERENCE*.md before releasing." -ErrorAction Continue
    exit 2
}

Write-Host "reindex-settings: OK - settings search index + navigation mirror already fresh, verify gate green." -ForegroundColor Green
exit 0
