package com.sza.fastmediasorter.ui.player.helpers

import android.net.Uri
import androidx.core.view.isVisible
import androidx.fragment.app.FragmentManager
import com.bumptech.glide.Glide
import com.sza.fastmediasorter.BuildConfig
import com.sza.fastmediasorter.R
import com.sza.fastmediasorter.databinding.ActivityPlayerUnifiedBinding
import com.sza.fastmediasorter.databinding.ViewMiniNowPlayingBinding
import com.sza.fastmediasorter.domain.model.MediaFile
import com.sza.fastmediasorter.ui.player.AudioPlaybackService
import com.sza.fastmediasorter.ui.player.NowPlayingBottomSheetFragment
import com.sza.fastmediasorter.ui.player.model.MediaItemWithMeta
import timber.log.Timber

/**
 * Manages the mini Now Playing bar inside PlayerActivity and launches
 * NowPlayingBottomSheetFragment on tap.
 *
 * Also provides [startPlayback] which builds [MediaItemWithMeta] items and
 * delegates to [AudioServiceController.playAudioPlaylistWithMetadata], enabling
 * per-track title/artist metadata in the MediaSession and system notification.
 *
 * Constructor-instantiated in PlayerActivity (same pattern as SleepTimerManager).
 * All playback commands are delegated — this manager holds no ExoPlayer reference.
 *
 * Entry points are guarded by [BuildConfig.ENABLE_PERSISTENT_AUDIO_PLAYBACK].
 */
class NowPlayingManager(
    private val activityBinding: ActivityPlayerUnifiedBinding,
    private val fragmentManager: FragmentManager,
    private val audioServiceController: AudioServiceController
) {

    // ViewMiniNowPlayingBinding is generated by ViewBinding for the <include> with id=miniNowPlayingBar
    private val miniBar: ViewMiniNowPlayingBinding = requireNotNull(activityBinding.miniNowPlayingBar)

    init {
        if (BuildConfig.ENABLE_PERSISTENT_AUDIO_PLAYBACK) {
            miniBar.root.setOnClickListener { showBottomSheet() }
            miniBar.miniPlayPause.setOnClickListener {
                audioServiceController.player?.let { player ->
                    if (player.isPlaying) player.pause() else player.play()
                    updateMiniPlayPauseIcon(player.isPlaying.not())
                }
            }
        }
    }

    /**
     * Build a metadata-enriched playlist and start playback via [AudioServiceController].
     *
     * @param files All audio files in the current list (same order as displayed in the player).
     * @param startIndex Index of the track to play first.
     * @param onPlayerReady Callback forwarded from the caller for binding the player to PlayerView.
     */
    fun startPlayback(
        files: List<MediaFile>,
        startIndex: Int,
        onPlayerReady: (androidx.media3.common.Player) -> Unit
    ) {
        if (!BuildConfig.ENABLE_PERSISTENT_AUDIO_PLAYBACK) return

        Timber.d("NowPlayingManager: startPlayback files=${files.size} startIndex=$startIndex")
        val items = files.map { file ->
            MediaItemWithMeta(
                uri = Uri.parse(file.path),
                title = file.name.substringBeforeLast('.'),
                artist = null,       // ID3 artist extracted natively by ExoPlayer after load
                albumArtUri = null   // cover art resolved lazily in ImageLoadingManager
            )
        }
        audioServiceController.playAudioPlaylistWithMetadata(items, startIndex, onPlayerReady)
    }

    /**
     * Called from PlayerActivity.onStart to refresh bar visibility and state.
     */
    fun onStart() {
        if (!BuildConfig.ENABLE_PERSISTENT_AUDIO_PLAYBACK) return
        updateBarVisibility()
    }

    /**
     * Update mini bar visibility and content based on service state.
     * Should be called whenever AudioPlaybackService.isRunning may have changed.
     */
    fun updateBarVisibility() {
        if (!BuildConfig.ENABLE_PERSISTENT_AUDIO_PLAYBACK) return

        val running = AudioPlaybackService.isRunning
        miniBar.root.isVisible = running
        Timber.d("NowPlayingManager: updateBarVisibility running=$running")

        if (running) {
            val player = audioServiceController.player
            if (player != null) {
                val meta = player.mediaMetadata
                miniBar.miniTitle.text = meta.title?.toString()
                    ?: activityBinding.root.context.getString(R.string.now_playing_label)
                val artworkUri = meta.artworkUri
                if (artworkUri != null) {
                    Glide.with(activityBinding.root.context)
                        .load(artworkUri)
                        .placeholder(R.drawable.ic_music_note)
                        .error(R.drawable.ic_music_note)
                        .into(miniBar.miniArtwork)
                } else {
                    miniBar.miniArtwork.setImageResource(R.drawable.ic_music_note)
                }
                updateMiniPlayPauseIcon(player.isPlaying)
            }
        }
    }

    private fun updateMiniPlayPauseIcon(isPlaying: Boolean) {
        miniBar.miniPlayPause.setImageResource(
            if (isPlaying) R.drawable.ic_pause else R.drawable.ic_play
        )
        miniBar.miniPlayPause.contentDescription = activityBinding.root.context.getString(
            if (isPlaying) R.string.now_playing_pause_desc else R.string.now_playing_play_desc
        )
    }

    private fun showBottomSheet() {
        if (fragmentManager.findFragmentByTag(NowPlayingBottomSheetFragment.TAG) != null) return
        Timber.d("NowPlayingManager: showing NowPlayingBottomSheetFragment")
        NowPlayingBottomSheetFragment.newInstance()
            .show(fragmentManager, NowPlayingBottomSheetFragment.TAG)
    }
}
