package com.sza.fastmediasorter.domain.model

/**
 * The exchange server the embedded SFTP server registers on to be reachable from any network
 * (contract ANYWHERE-ACCESS section 5). Off by default: with [enabled] false the server behaves
 * exactly as the LAN-only server of S3041 (contract section 8).
 */
data class SftpExchangeConfig(
    val enabled: Boolean,
    val host: String,
    val port: Int,
    /** Plain server password, or null when none was set or the stored cipher text is unreadable. */
    val password: String?,
    /** The share id of contract section 6.2; generated by the producer, never by the server. */
    val shareId: String,
    /** `SHA256:<base64-no-padding>` of the server's leaf certificate, pinned on first registration. */
    val pinnedCertificate: String?,
) {

    /** Everything a registration needs is present and well-formed. */
    val isUsable: Boolean
        get() = enabled && host.isNotBlank() && port in 1..MAX_PORT &&
            SftpExchangePasswordPolicy.accepts(password) && SftpShareId.isValid(shareId)

    /** The `host:port` form the `FMSSFTP2` descriptor carries as `x`; an IPv6 literal goes in brackets. */
    fun endpoint(): String = (if (':' in host) "[$host]" else host) + ":$port"

    companion object {
        const val DEFAULT_PORT = 44_022
        const val MAX_PORT = 65_535
    }
}

/** The owner's floor for an exchange server password (contract section 5.2, 2026-10-05). */
object SftpExchangePasswordPolicy {

    const val MIN_LENGTH = 10

    fun accepts(password: String?): Boolean =
        password != null && password.length >= MIN_LENGTH &&
            password.any { it in 'A'..'Z' } && password.any { it in 'a'..'z' } && password.any { it in '0'..'9' }
}

/** What the producer's registration on the exchange server is doing. */
sealed interface SftpTunnelState {
    /** No exchange server configured, or the SFTP server is not running. */
    object Off : SftpTunnelState

    object Connecting : SftpTunnelState

    /** Registered; [publicPort] is the third-party port the server granted, if any (contract section 5.5). */
    data class Registered(val publicPort: Int?) : SftpTunnelState

    /** The server refused; [reason] is a contract section 6.3 reason string. Retries stop for a credential refusal. */
    data class Refused(val reason: String) : SftpTunnelState

    /** The server answered with a certificate other than the pinned one; retries stop until the pin is reset. */
    object CertificateChanged : SftpTunnelState

    /** The server could not be reached; the manager keeps retrying with backoff. */
    object Unreachable : SftpTunnelState
}
