<#
.SYNOPSIS
    Fast per-flavor Gradle check - compile, resources, unit tests or assemble. Defaults to app_v2;
    -Module wear checks the Wear OS module, which has no product flavors.

.OUTPUTS
    Exit 0 - the check passed.
    Exit 1 - the check found a defect (compile error, red test, truncated suite).
    Exit 2 - the check could not run to a verdict (S1463: the unit-test worker JVM died, twice;
             -Flavor was combined with -Module wear, which declares no flavors; or
             -BuildType Release was combined with -Mode Assemble, which is refused - see below).
#>
param(
    [ValidateSet("Code", "Resources", "CodeAndResources", "Unit", "AndroidTest", "Assemble")]
    [string]$Mode = "CodeAndResources",
    # S0826: per-flavor fast compile check. Standard is the default; NoLegal needs its own
    # path because it bundles Python via Chaquopy (see flag handling below).
    # S0404: the capability-gated flavors (Lite / Photos / Legacy) compile the no-op source sets,
    # so a seam change needs a fast check on one of them too.
    # S0989: Vr compiles the src/vr source set (OpenXR immersive host) - needed when a change
    # lives only under src/vr, which the Standard/NoLegal checks never compile.
    [ValidateSet("Standard", "NoLegal", "Lite", "Photos", "Legacy", "Vr")]
    [string]$Flavor = "Standard",
    # S1496: wear is an active Gradle module with no fast check of its own, which is how its jsch
    # pin drifted nine minor versions behind app_v2 unnoticed. It declares no product flavors, so
    # -Flavor does not apply to it.
    [ValidateSet("app_v2", "wear")]
    [string]$Module = "app_v2",
    # S1988: which build type the check compiles. Debug is the working default and the only one any
    # caller used before, but it compiles src/debug ALONGSIDE src/main, so it cannot answer the one
    # question a debug-only test seam raises: does src/main still build when the debug class is gone?
    # `.\a.ps1 nl` looks like that proof and is not - release targets delegate to the git worktree at
    # ../FastMediaSorter_release and build main, so they never see the working tree's changes.
    [ValidateSet("Debug", "Release")]
    [string]$BuildType = "Debug",
    [string]$Tests,
    # S1735: system properties forwarded to the gradle JVM, "name=value" each.
    #
    # Some maintained artifacts are REGENERATED by a test rather than by a script - the settings manifest
    # is written by SettingsManifestExportTest under -Dsettings.manifest.generate=true, and its gate tells
    # you to run exactly that. Without a passthrough the only way to obey the gate was to call gradlew.bat
    # directly, which Rule 23 forbids because it bypasses temp/BUILD.LOCK. The gap made the sanctioned
    # path and the documented path contradict each other.
    [string[]]$SystemProperty,
    [switch]$Quiet
)

$ErrorActionPreference = "Stop"

. "$PSScriptRoot\..\utils\agent-lock.ps1"
. "$PSScriptRoot\gradle-run-verdict.ps1"
Enter-BuildLockOrExit -Reason "check-standard-fast.ps1"
try {

$projectRoot = Resolve-Path "$PSScriptRoot\..\.."
Set-Location $projectRoot

if ($Module -eq 'wear' -and $Flavor -ne 'Standard') {
    Write-Error "check-standard-fast: -Flavor '$Flavor' is meaningless for the wear module - it declares no product flavors." -ErrorAction Continue
    exit 2
}

# S1988/S1873: -Mode Assemble is the only mode that packages an installable artifact, and its version
# stamp below is written for a debug build. A release APK produced here would be unsigned and stamped
# wrong while looking exactly like the real thing, which is the failure S1873 records. Release
# packaging belongs to the release worktree; this script only ever compiles a release variant.
if ($BuildType -eq 'Release' -and $Mode -eq 'Assemble') {
    Write-Error "check-standard-fast: -BuildType Release is refused with -Mode Assemble - use the release worktree (.\a.ps1 r / nl / vr) to package." -ErrorAction Continue
    exit 2
}

# The wear module declares no product flavors, so its task names carry no flavor segment.
$variant = if ($Module -eq 'wear') { '' } else { $Flavor }

function Get-GradleTaskList {
    switch ($Mode) {
        "Code" { return @(":${Module}:compile${variant}${BuildType}Kotlin") }
        "Resources" { return @(":${Module}:process${variant}${BuildType}Resources") }
        "CodeAndResources" { return @(":${Module}:compile${variant}${BuildType}Kotlin", ":${Module}:process${variant}${BuildType}Resources") }
        "Unit" { return @(":${Module}:test${variant}${BuildType}UnitTest") }
        # S1832: nothing compiled the instrumented source set, which is how
        # AppDatabaseMigration50To51Test shipped referencing an undeclared constant. Compile only -
        # running these needs a device, but a test that cannot build is never going to run anywhere.
        "AndroidTest" { return @(":${Module}:compile${variant}${BuildType}AndroidTestKotlin") }
        "Assemble" { return @(":${Module}:assemble${variant}Debug") }
        default { throw "Unsupported mode: $Mode" }
    }
}

$gradleArgs = New-Object System.Collections.Generic.List[string]
Get-GradleTaskList | ForEach-Object { $null = $gradleArgs.Add($_) }
# Flavors without Python: disable Chaquopy and use the configuration cache for speed.
# NoLegal bundles Python via Chaquopy, whose API must stay on the compile classpath and
# whose tasks are not configuration-cache serialisable - so keep it enabled and skip the cache.
if ($Flavor -ne "NoLegal") {
    $null = $gradleArgs.Add("-Pchaquopy.enabled=false")
    $null = $gradleArgs.Add("--configuration-cache")
}

foreach ($property in $SystemProperty) {
    $trimmed = $property.Trim()
    if (-not $trimmed) { continue }
    if ($trimmed -notmatch '^[^=\s]+=.*$') {
        throw "-SystemProperty expects 'name=value', got '$property'"
    }
    $null = $gradleArgs.Add("-D$trimmed")
}

if ($Mode -eq "Assemble") {
    # -Mode Assemble is the only mode here that packages a real, installable APK. Left unstamped it
    # ships the checked-in constant, so the artifact reports the version of whatever release last
    # touched build.gradle.kts - on 2026-08-21 that installed a watch build reading six days older
    # than the one it replaced (S1873). Every compile-only mode keeps the frozen value on purpose.
    . "$PSScriptRoot\..\utils\build-version-stamp.ps1"
    $stamp = Get-BuildVersionStamp
    $assembleVersionCode = if ($Module -eq 'wear') { $stamp.WearVersionCode } else { $stamp.AppVersionCode }
    $null = $gradleArgs.Add("-Pfms.versionCode=$assembleVersionCode")
    $null = $gradleArgs.Add("-Pfms.versionName=$($stamp.VersionName)")
    Write-Host "Version override: $($stamp.VersionName) (code: $assembleVersionCode)" -ForegroundColor Green
}

if ($Tests) {
    if ($Mode -ne "Unit") {
        throw "-Tests is supported only with -Mode Unit"
    }
    # Gradle takes ONE pattern per --tests flag and does not split on commas: passing
    # "*ATest,*BTest" as a single argument makes it look for a class literally named that, and it
    # answers "No tests found for given includes" - which reads as "your tests are gone" rather
    # than "your filter was malformed" (S1449). Split here so a comma-separated list means what
    # every caller assumes it means.
    foreach ($pattern in ($Tests -split ',' | ForEach-Object { $_.Trim() } | Where-Object { $_ })) {
        $null = $gradleArgs.Add("--tests")
        $null = $gradleArgs.Add($pattern)
    }
}

# S1807: the label names the module, not only the flavor. This banner is what gets pasted into a
# step log as proof, and with two active modules a phone verdict quoted under a wear ticket has to
# read as foreign rather than as confirmation.
$checkLabel = if ($Module -eq 'wear') { 'wear' } else { "app_v2/$Flavor" }
Write-Host "Fast $checkLabel check.." -ForegroundColor Cyan
Write-Host "Mode: $Mode" -ForegroundColor Yellow
Write-Host "Build type: $BuildType" -ForegroundColor Yellow
if ($Tests) {
    Write-Host "Tests filter: $Tests" -ForegroundColor Yellow
}
Write-Host "Command: .\\gradlew.bat $($gradleArgs -join ' ')" -ForegroundColor DarkGray

$runOnce = {
    param([int]$Attempt)

    $collected = New-Object System.Collections.Generic.List[string]
    & "$projectRoot\gradlew.bat" @gradleArgs 2>&1 | ForEach-Object {
        $line = [string]$_
        $collected.Add($line)
        if ($Quiet -and ($line -match " UP-TO-DATE$" -or $line -match " NO-SOURCE$" -or $line -match " FROM-CACHE$")) {
            return
        }
        Write-Host $line
    }
    return [pscustomobject]@{ ExitCode = $LASTEXITCODE; Lines = $collected.ToArray() }
}

# S1463: only a unit run can lose its worker, and only there is a repeat the right answer - repeating
# a failed compile would just double the wait for an error that is not going to change.
$run = if ($Mode -eq "Unit") {
    Invoke-GradleRunWithRetry -RunOnce $runOnce -MaxAttempts 2
} else {
    # Same shape on both branches on purpose: a caller that probes .WorkerDeath must not depend on
    # which branch produced the object (the strict-mode property probe that broke S1462).
    $single = & $runOnce 1
    [pscustomobject]@{ ExitCode = $single.ExitCode; Lines = $single.Lines; Attempts = 1; WorkerDeath = $false }
}

$gradleExit = $run.ExitCode

# S1244: a truncated unit run ALWAYS ends non-zero - the worker process dies. So the completeness
# check has to run BEFORE the exit-code bail-out below; placed after it, the one run it exists to
# catch would exit first and never reach it. Skipped for a --tests filter, where a handful of
# reports is the correct outcome rather than a truncation.
if ($Mode -eq "Unit" -and -not $Tests) {
    & "$PSScriptRoot\..\quality\assert-test-suite-complete.ps1" -Module $Module -TaskDir "test${variant}DebugUnitTest"
    $gateExit = $LASTEXITCODE
    if ($gateExit -eq 1 -and -not $run.WorkerDeath) {
        Write-Host "`nFast check failed - the unit run did not cover the whole suite." -ForegroundColor Red
        exit 1
    }
    # Exit 2 is "could not check" (no reports yet). Say so, but let a real Gradle failure below own
    # the verdict rather than masking it with a missing-reports message.
    if ($gateExit -eq 2) {
        Write-Host "Suite-completeness check could not run; coverage is unverified." -ForegroundColor Yellow
    }
}

# S1463: the worker JVM dying is not a test result. Reported as exit 1 it is indistinguishable from a
# red test, and the reader spends the next hour hunting a failure that never happened. Exit 2 is this
# repo's "could not verify" (S1338), and it is the honest answer: nothing was proven either way.
if ($run.WorkerDeath) {
    $msg = "check-standard-fast: the Gradle test worker died on both attempts - this run produced NO " +
    "verdict. Nothing was proven about the tests; do not read it as a failure. Usual cause is host " +
    "load (concurrent Gradle daemons or emulators). Re-run on a quiet host; see PLAN/S1463."
    Write-Error $msg -ErrorAction Continue
    exit 2
}

if ($gradleExit -ne 0) {
    Write-Host "`nFast check failed." -ForegroundColor Red
    # S1786: auto-emit structured failure digest from the current run's log
    $bfdScript = Join-Path $PSScriptRoot "build-failure-digest.ps1"
    if (Test-Path $bfdScript) {
        $tempLogPath = Join-Path $projectRoot "temp/check_fast_$(Get-Date -Format 'yyyyMMdd_HHmmss').log"
        if ($run.Lines -and $run.Lines.Length -gt 0) {
            [System.IO.File]::WriteAllLines($tempLogPath, $run.Lines, [System.Text.UTF8Encoding]::new($false))
            Write-Host "`n--- Build Failure Digest ---" -ForegroundColor Yellow
            & $bfdScript -LogPath $tempLogPath
        }
    }
    exit $gradleExit
}

Write-Host "`nFast check passed." -ForegroundColor Green

# S1920: name the directory Gradle actually wrote to. A --tests run may report into a directory of its
# own (`<task>-filtered`) while the plain one keeps whatever the last FULL run left there, so a reader
# who checks the obvious path sees another run's counts under this run's green line - three sessions
# have now read the wrong one and concluded a passing test never ran.
# S1946: which of the two receives them is not fixed - the same call filtered into `-filtered` on
# app_v2 and into the plain directory on wear - so this reports the newest match instead of naming a
# path from a rule. A guess here would recreate the very failure the line exists to prevent.
if ($Tests -and $Mode -eq "Unit") {
    $resultsRoot = Join-Path $projectRoot "$Module\build\test-results"
    $written = if (Test-Path $resultsRoot) {
        Get-ChildItem -Path $resultsRoot -Directory |
            Where-Object { $_.Name -like "test*UnitTest*" } |
            Sort-Object LastWriteTime -Descending |
            Select-Object -First 1
    } else {
        $null
    }
    if ($written) {
        Write-Host "Reports (this filtered run): $($written.FullName)" -ForegroundColor Yellow
    }
}

}
finally {
    Exit-AgentLock -Name Build
}
