<#
.SYNOPSIS
    Fast per-module, per-flavor Gradle check - compile, resources, unit tests, instrumented tests on a
    connected device (-Mode ConnectedAndroidTest, the only mode needing one) or assemble. Defaults
    to app_v2. Every module in scripts/utils/gradle-modules.ps1 is accepted, including one with no
    flavor dimension, whose task names carry no variant segment (:watchface:processDebugResources).

.OUTPUTS
    Exit 0 - the check passed.
    Exit 1 - the check found a defect (compile error, red test, truncated suite).
    Exit 2 - the check could not run to a verdict (S1463: the unit-test worker JVM died, twice;
             -Module named a project the registry does not know; -Flavor named one the module does
             not declare, or was passed to a module that declares none; -BuildType named a build type
             the module does not declare, or the module declares none at all (S2123 - lint-rules has
             no Android plugin); or -BuildType Release was combined with -Mode Assemble, which is
             refused - see below).
#>
param(
    [ValidateSet("Code", "Resources", "CodeAndResources", "Unit", "AndroidTest", "ConnectedAndroidTest", "Assemble")]
    [string]$Mode = "CodeAndResources",
    # S0826: per-flavor fast compile check. Standard is the default; NoLegal needs its own
    # path because it bundles Python via Chaquopy (see flag handling below).
    # S0404: the capability-gated flavors (Lite / Photos / Legacy) compile the no-op source sets,
    # so a seam change needs a fast check on one of them too.
    # S0989: Vr compiles the src/vr source set (OpenXR immersive host) - needed when a change
    # lives only under src/vr, which the Standard/NoLegal checks never compile.
    # S2121: no ValidateSet. The accepted values differ per module - watchface declares none at all -
    # so the check is a registry lookup below, and left unbound this resolves to the module's own
    # first flavor rather than to a literal "Standard" a flavorless module cannot name.
    [string]$Flavor,
    # S1496: wear is an active Gradle module with no fast check of its own, which is how its jsch
    # pin drifted nine minor versions behind app_v2 unnoticed.
    # S2090: wear now declares its own two-flavor `version` dimension, so -Flavor applies to it too -
    # but only over Standard and NoLegal. The per-module allowed set is checked below.
    # S2121: the module list moved to scripts/utils/gradle-modules.ps1 - one table, read by the
    # closure facade's resource-link gate too. A ValidateSet here was a third copy of it.
    [string]$Module = "app_v2",
    # S1988: which build type the check compiles. Debug is the working default and the only one any
    # caller used before, but it compiles src/debug ALONGSIDE src/main, so it cannot answer the one
    # question a debug-only test seam raises: does src/main still build when the debug class is gone?
    # `.\a.ps1 nl` looks like that proof and is not - release targets delegate to the git worktree at
    # ../FastMediaSorter_release and build main, so they never see the working tree's changes.
    # S2123: no ValidateSet, for the same reason -Flavor lost its one in S2121 - the accepted values
    # differ per module. :benchmark declares neither Debug nor Release: androidx.baselineprofile gives
    # it nonMinifiedRelease and benchmarkRelease, so a two-value ValidateSet made every call to that
    # module name a task gradle has never had. Left unbound this resolves to the module's own default
    # (its first declared build type), which is still Debug for the three ordinary Android modules.
    [string]$BuildType,
    [string]$Tests,
    # S1735: system properties forwarded to the gradle JVM, "name=value" each.
    #
    # Some maintained artifacts are REGENERATED by a test rather than by a script - the settings manifest
    # is written by SettingsManifestExportTest under -Dsettings.manifest.generate=true, and its gate tells
    # you to run exactly that. Without a passthrough the only way to obey the gate was to call gradlew.bat
    # directly, which Rule 23 forbids because it bypasses temp/BUILD.LOCK. The gap made the sanctioned
    # path and the documented path contradict each other.
    [string[]]$SystemProperty,
    [switch]$Quiet
)

$ErrorActionPreference = "Stop"

. "$PSScriptRoot\..\utils\agent-lock.ps1"
. "$PSScriptRoot\..\utils\gradle-modules.ps1"
. "$PSScriptRoot\gradle-run-verdict.ps1"

# S2121: validate the module BEFORE taking a lock or launching gradle. An unknown module used to be
# impossible here only because a ValidateSet listed two of the five projects the build declares;
# with the registry it is a real input, and the honest answer is "could not check" rather than a
# task name guessed for a project that may not exist.
if (-not (Test-GradleModuleName -Name $Module)) {
    $knownModules = (Get-GradleModuleNames) -join ', '
    Write-Error "check-standard-fast: -Module '$Module' is not a registered Gradle module - known modules are $knownModules. Add a row in scripts/utils/gradle-modules.ps1 if the build declares it." -ErrorAction Continue
    exit 2
}

# S2090: each module declares its own flavor set, so the allowed values are per-module rather than one
# ValidateSet. Naming what the module DOES accept matters more than naming what it rejected: the wear
# set is a strict subset of the phone's, so the plausible mistake is asking for a phone-only flavor.
# S2121: the sets live in the registry now, and an EMPTY set is a real answer - watchface declares no
# flavor dimension at all, so its task names carry no variant segment. Resolved before the lock for
# the same reason the toolchain check is: a refusal must not first take a place in every sibling's
# queue and then decline to build anything.
$declaredFlavors = @(Get-GradleModuleFlavors -Name $Module)
if ($PSBoundParameters.ContainsKey('Flavor') -and $Flavor) {
    if ($declaredFlavors.Count -eq 0) {
        Write-Error "check-standard-fast: -Flavor '$Flavor' was passed to '$Module', which declares no product flavors - omit -Flavor for this module." -ErrorAction Continue
        exit 2
    }
    if ($declaredFlavors -notcontains $Flavor) {
        Write-Error "check-standard-fast: -Flavor '$Flavor' does not exist in the '$Module' module - it declares $($declaredFlavors -join ', ')." -ErrorAction Continue
        exit 2
    }
}
else {
    # Unbound means "the module's default variant" - its first declared flavor, or none at all. A
    # literal "Standard" default would name a variant a flavorless module has never had.
    $Flavor = if ($declaredFlavors.Count -gt 0) { $declaredFlavors[0] } else { '' }
}

# S2123: the build type is validated against the registry exactly as the flavor is, and for the same
# reason - it is the other half of the variant name, and it was the half left hardcoded. Resolved
# before the lock too: a refusal must not first take a place in every sibling's queue.
$declaredBuildTypes = @(Get-GradleModuleBuildTypes -Name $Module)
if ($PSBoundParameters.ContainsKey('BuildType') -and $BuildType) {
    if ($declaredBuildTypes.Count -eq 0) {
        Write-Error "check-standard-fast: -BuildType '$BuildType' was passed to '$Module', which declares no build types at all - it has no Android plugin, so no variant task exists for it." -ErrorAction Continue
        exit 2
    }
    if ($declaredBuildTypes -notcontains $BuildType) {
        Write-Error "check-standard-fast: -BuildType '$BuildType' does not exist in the '$Module' module - it declares $($declaredBuildTypes -join ', ')." -ErrorAction Continue
        exit 2
    }
}
else {
    if ($declaredBuildTypes.Count -eq 0) {
        Write-Error "check-standard-fast: '$Module' declares no build types - it has no Android plugin, so there is no task for this check to run." -ErrorAction Continue
        exit 2
    }
    $BuildType = Get-GradleModuleDefaultBuildType -Name $Module
}

# S1988/S1873: -Mode Assemble is the only mode that packages an installable artifact, and its version
# stamp below is written for a debug build. A release APK produced here would be unsigned and stamped
# wrong while looking exactly like the real thing, which is the failure S1873 records. Release
# packaging belongs to the release worktree; this script only ever compiles a release variant.
if ($BuildType -eq 'Release' -and $Mode -eq 'Assemble') {
    Write-Error "check-standard-fast: -BuildType Release is refused with -Mode Assemble - use the release worktree (.\a.ps1 r / nl / vr) to package." -ErrorAction Continue
    exit 2
}

# S2109: the domain is derived from -Module - ADR-1 wants the domain read off data the call carries,
# not declared a second time and left to drift from it.
# S2121: the derivation moved into the registry, so a module with no domain of its own widens to the
# full build set (ADR-2) instead of silently taking the phone's and serialising against nothing.
$buildDomains = @(Get-GradleModuleBuildDomains -Name $Module)
Enter-BuildLockOrExit -Reason "check-standard-fast.ps1 ($Module)" -Domain $buildDomains
try {

$projectRoot = Resolve-Path "$PSScriptRoot\..\.."
Set-Location $projectRoot

# S2090: both app modules carry a flavor dimension, so their task names get the segment. Before this,
# wear substituted an empty segment - a task name gradle stopped having the moment the dimension existed.
# S2121: a module that declares NO dimension is the mirror case and needs the empty segment back -
# :watchface:processDebugResources is the real task name, and interpolating any variant into it names
# a task gradle has never had.
$variant = $Flavor

function Get-GradleTaskList {
    switch ($Mode) {
        "Code" { return @(":${Module}:compile${variant}${BuildType}Kotlin") }
        "Resources" { return @(":${Module}:process${variant}${BuildType}Resources") }
        "CodeAndResources" { return @(":${Module}:compile${variant}${BuildType}Kotlin", ":${Module}:process${variant}${BuildType}Resources") }
        "Unit" { return @(":${Module}:test${variant}${BuildType}UnitTest") }
        # S1832: nothing compiled the instrumented source set, which is how
        # AppDatabaseMigration50To51Test shipped referencing an undeclared constant. Compile only -
        # running these needs a device, but a test that cannot build is never going to run anywhere.
        "AndroidTest" { return @(":${Module}:compile${variant}${BuildType}AndroidTestKotlin") }
        # S2306: the only mode that RUNS the instrumented set, which is the only way a Room migration
        # is ever executed against real SQLite before a user's phone does it. Compiling these proves
        # they parse; runMigrationsAndValidate is the same schema comparison the device performs on
        # the first launch after an update, and until this mode existed nothing in the repository ever
        # performed it - S2251 shipped a migration whose column the entity did not declare, and the
        # first execution of that comparison anywhere was on the owner's phone, which then reset the
        # database. Needs a connected device or emulator.
        "ConnectedAndroidTest" { return @(":${Module}:connected${variant}${BuildType}AndroidTest") }
        "Assemble" { return @(":${Module}:assemble${variant}Debug") }
        default { throw "Unsupported mode: $Mode" }
    }
}

$gradleArgs = New-Object System.Collections.Generic.List[string]
Get-GradleTaskList | ForEach-Object { $null = $gradleArgs.Add($_) }
# Flavors without Python: disable Chaquopy and use the configuration cache for speed.
# NoLegal bundles Python via Chaquopy, whose API must stay on the compile classpath and
# whose tasks are not configuration-cache serialisable - so keep it enabled and skip the cache.
if ($Flavor -ne "NoLegal") {
    $null = $gradleArgs.Add("-Pchaquopy.enabled=false")
    $null = $gradleArgs.Add("--configuration-cache")
}

foreach ($property in $SystemProperty) {
    $trimmed = $property.Trim()
    if (-not $trimmed) { continue }
    if ($trimmed -notmatch '^[^=\s]+=.*$') {
        throw "-SystemProperty expects 'name=value', got '$property'"
    }
    $null = $gradleArgs.Add("-D$trimmed")
}

if ($Mode -eq "Assemble") {
    # -Mode Assemble is the only mode here that packages a real, installable APK. Left unstamped it
    # ships the checked-in constant, so the artifact reports the version of whatever release last
    # touched build.gradle.kts - on 2026-08-21 that installed a watch build reading six days older
    # than the one it replaced (S1873). Every compile-only mode keeps the frozen value on purpose.
    . "$PSScriptRoot\..\utils\build-version-stamp.ps1"
    $stamp = Get-BuildVersionStamp
    $assembleVersionCode = if ($Module -eq 'wear') { $stamp.WearVersionCode } else { $stamp.AppVersionCode }
    $null = $gradleArgs.Add("-Pfms.versionCode=$assembleVersionCode")
    $null = $gradleArgs.Add("-Pfms.versionName=$($stamp.VersionName)")
    Write-Host "Version override: $($stamp.VersionName) (code: $assembleVersionCode)" -ForegroundColor Green
}

if ($Tests -and $Mode -eq "ConnectedAndroidTest") {
    # S2306: the connected task takes no `--tests` - filtering an instrumented run is the runner's
    # job, not Gradle's, so the value is forwarded as an AndroidJUnitRunner argument. Passing a Gradle
    # glob here would be accepted silently and run the WHOLE instrumented suite on the device, which
    # reads as a much stronger verdict than it is.
    #
    # The runner has TWO arguments and they are not interchangeable: `class` takes a fully qualified
    # class (or Class#method), `package` takes a package. Handing a package to `class` matches nothing -
    # and "no tests found" is the worst possible outcome here, because it is a run that proved nothing
    # while looking like one that ran. They are told apart by the Java convention every name in this
    # repository follows: a final segment starting lower-case is a package, upper-case is a class.
    $tokens = @($Tests -split ',' | ForEach-Object { $_.Trim() } | Where-Object { $_ })
    $packages = @($tokens | Where-Object { ($_ -split '\.')[-1] -cmatch '^[a-z]' })
    $classes = @($tokens | Where-Object { $packages -notcontains $_ })
    if ($packages.Count -gt 0 -and $classes.Count -gt 0) {
        throw "-Tests mixes package names ($($packages -join ', ')) with class names ($($classes -join ', ')). The instrumentation runner takes one or the other, so name only packages or only classes."
    }
    if ($packages.Count -gt 0) {
        $null = $gradleArgs.Add("-Pandroid.testInstrumentationRunnerArguments.package=$($packages -join ',')")
    }
    else {
        $null = $gradleArgs.Add("-Pandroid.testInstrumentationRunnerArguments.class=$($classes -join ',')")
    }
}
elseif ($Tests) {
    if ($Mode -ne "Unit") {
        throw "-Tests is supported only with -Mode Unit or -Mode ConnectedAndroidTest"
    }
    # Gradle takes ONE pattern per --tests flag and does not split on commas: passing
    # "*ATest,*BTest" as a single argument makes it look for a class literally named that, and it
    # answers "No tests found for given includes" - which reads as "your tests are gone" rather
    # than "your filter was malformed" (S1449). Split here so a comma-separated list means what
    # every caller assumes it means.
    foreach ($pattern in ($Tests -split ',' | ForEach-Object { $_.Trim() } | Where-Object { $_ })) {
        $null = $gradleArgs.Add("--tests")
        $null = $gradleArgs.Add($pattern)
    }
}

# S1807: the label names the module, not only the flavor. This banner is what gets pasted into a
# step log as proof, and with two active modules a phone verdict quoted under a wear ticket has to
# read as foreign rather than as confirmation.
# S2090: it now names the flavor for BOTH modules. wear used to print a bare 'wear' because it had one
# variant; with two, a bare module name states half of what was checked.
# S2121: a module with no flavor dimension prints its bare name - "watchface/" would read as a
# variant whose name got lost, which is the opposite of what the banner is for.
$checkLabel = if ($Flavor) { "$Module/$Flavor" } else { $Module }
Write-Host "Fast $checkLabel check.." -ForegroundColor Cyan
Write-Host "Mode: $Mode" -ForegroundColor Yellow
Write-Host "Build type: $BuildType" -ForegroundColor Yellow
if ($Tests) {
    Write-Host "Tests filter: $Tests" -ForegroundColor Yellow
}
Write-Host "Command: .\\gradlew.bat $($gradleArgs -join ' ')" -ForegroundColor DarkGray

# S2127: set by the repair block below, read by the runner on the retry. A closure rather than a
# rebuilt argument list so the first attempt's command line - the one printed above as evidence - is
# the one that actually ran.
$script:kotlinIncrementalDisabled = $false

$runOnce = {
    param([int]$Attempt)

    $attemptArgs = @($gradleArgs)
    if ($script:kotlinIncrementalDisabled) {
        $attemptArgs += Get-KotlinStaleIncrementalRepairArgs
    }

    $collected = New-Object System.Collections.Generic.List[string]
    & "$projectRoot\gradlew.bat" @attemptArgs 2>&1 | ForEach-Object {
        $line = [string]$_
        $collected.Add($line)
        if ($Quiet -and ($line -match " UP-TO-DATE$" -or $line -match " NO-SOURCE$" -or $line -match " FROM-CACHE$")) {
            return
        }
        Write-Host $line
    }
    return [pscustomobject]@{ ExitCode = $LASTEXITCODE; Lines = $collected.ToArray() }
}

# S1463: only a unit run can lose its worker, and only there is a repeat the right answer - repeating
# a failed compile would just double the wait for an error that is not going to change.
# S2127: one failed compile IS worth repeating - the one whose error names a class the incremental
# state lost rather than a class the sources lack. Both branches go through the wrapper now, so every
# mode gets that repair; the retry policy stays bound to its two signatures and to nothing else, which
# is what keeps an ordinary red compile a single attempt on either branch.
$repairStaleState = { $script:kotlinIncrementalDisabled = $true }
$run = Invoke-GradleRunWithRetry -RunOnce $runOnce -MaxAttempts 2 `
    -RepairStaleIncrementalState $repairStaleState

$gradleExit = $run.ExitCode

# S1244: a truncated unit run ALWAYS ends non-zero - the worker process dies. So the completeness
# check has to run BEFORE the exit-code bail-out below; placed after it, the one run it exists to
# catch would exit first and never reach it. Skipped for a --tests filter, where a handful of
# reports is the correct outcome rather than a truncation.
if ($Mode -eq "Unit" -and -not $Tests) {
    & "$PSScriptRoot\..\quality\assert-test-suite-complete.ps1" -Module $Module -TaskDir "test${variant}DebugUnitTest"
    $gateExit = $LASTEXITCODE
    if ($gateExit -eq 1 -and -not $run.WorkerDeath) {
        Write-Host "`nFast check failed - the unit run did not cover the whole suite." -ForegroundColor Red
        exit 1
    }
    # Exit 2 is "could not check" (no reports yet). Say so, but let a real Gradle failure below own
    # the verdict rather than masking it with a missing-reports message.
    if ($gateExit -eq 2) {
        Write-Host "Suite-completeness check could not run; coverage is unverified." -ForegroundColor Yellow
    }
}

# S1463: the worker JVM dying is not a test result. Reported as exit 1 it is indistinguishable from a
# red test, and the reader spends the next hour hunting a failure that never happened. Exit 2 is this
# repo's "could not verify" (S1338), and it is the honest answer: nothing was proven either way.
if ($run.WorkerDeath) {
    $msg = "check-standard-fast: the Gradle test worker died on both attempts - this run produced NO " +
    "verdict. Nothing was proven about the tests; do not read it as a failure. Usual cause is host " +
    "load (concurrent Gradle daemons or emulators). Re-run on a quiet host; see PLAN/S1463."
    Write-Error $msg -ErrorAction Continue
    exit 2
}

if ($gradleExit -ne 0) {
    Write-Host "`nFast check failed." -ForegroundColor Red
    # S1786: auto-emit structured failure digest from the current run's log
    $bfdScript = Join-Path $PSScriptRoot "build-failure-digest.ps1"
    if (Test-Path $bfdScript) {
        $tempLogPath = Join-Path $projectRoot "temp/check_fast_$(Get-Date -Format 'yyyyMMdd_HHmmss').log"
        if ($run.Lines -and $run.Lines.Length -gt 0) {
            [System.IO.File]::WriteAllLines($tempLogPath, $run.Lines, [System.Text.UTF8Encoding]::new($false))
            Write-Host "`n--- Build Failure Digest ---" -ForegroundColor Yellow
            & $bfdScript -LogPath $tempLogPath
        }
    }
    exit $gradleExit
}

Write-Host "`nFast check passed." -ForegroundColor Green

# S1920: name the directory Gradle actually wrote to. A --tests run may report into a directory of its
# own (`<task>-filtered`) while the plain one keeps whatever the last FULL run left there, so a reader
# who checks the obvious path sees another run's counts under this run's green line - three sessions
# have now read the wrong one and concluded a passing test never ran.
# S1946: which of the two receives them is not fixed - the same call filtered into `-filtered` on
# app_v2 and into the plain directory on wear - so this reports the newest match instead of naming a
# path from a rule. A guess here would recreate the very failure the line exists to prevent.
if ($Tests -and $Mode -eq "Unit") {
    $resultsRoot = Join-Path $projectRoot "$Module\build\test-results"
    $written = if (Test-Path $resultsRoot) {
        Get-ChildItem -Path $resultsRoot -Directory |
            Where-Object { $_.Name -like "test*UnitTest*" } |
            Sort-Object LastWriteTime -Descending |
            Select-Object -First 1
    } else {
        $null
    }
    if ($written) {
        Write-Host "Reports (this filtered run): $($written.FullName)" -ForegroundColor Yellow
    }
}

}
finally {
    # Release exactly the domain taken above - a bare Build here would free the other module's
    # domain, which this run never held and a sibling may be building in right now.
    Exit-AgentLock -Name 'Build' -Domains $buildDomains
}
