package com.sza.fastmediasorter.data.local.db

import androidx.room.Dao
import androidx.room.Entity
import androidx.room.Index
import androidx.room.Insert
import androidx.room.PrimaryKey
import androidx.room.Query
import kotlinx.coroutines.flow.Flow

/**
 * S1433: one finished manual measurement of the Network Monitor, kept so the user can compare runs.
 *
 * Only measurements the user started by hand land here. Strategic §3.2 keeps the live charts and the
 * satellite list in memory for the lifetime of the open screen, so no observer writes rows.
 *
 * There is deliberately no column for an external IP address and none for a secret of any kind:
 * strategic §3.2 forbids storing either, and a row shape that cannot hold them is what enforces that
 * against every later caller. The external-IP check therefore records its outcome in [resultText] and
 * never the address it saw.
 *
 * [kind] is TEXT holding the domain enum's name rather than an ordinal, so reordering the enum cannot
 * silently re-label rows already on disk. [downMbps], [upMbps] and [latencyMs] are nullable because
 * most kinds fill none of them - a subnet scan has no throughput, and zero would read as a measured
 * zero rather than "not part of this measurement".
 */
@Entity(
    tableName = "network_measurement",
    indices = [Index(value = ["takenAtMillis"])]
)
data class NetworkMeasurementEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0L,
    val takenAtMillis: Long,
    val kind: String,
    val networkLabel: String,
    val downMbps: Double?,
    val upMbps: Double?,
    val latencyMs: Long?,
    val resultText: String,
    val succeeded: Boolean
)

/**
 * S1433: storage access for the measurement history.
 *
 * Every read and every trim orders by `takenAtMillis DESC, id DESC`. The timestamp alone is not a total
 * order - two measurements that finish in the same millisecond would tie, and a tie makes the retention
 * trim pick arbitrarily between them - so the autogenerated id breaks it.
 */
@Dao
interface NetworkMeasurementDao {

    @Insert
    suspend fun insert(measurement: NetworkMeasurementEntity): Long

    @Query("SELECT * FROM network_measurement ORDER BY takenAtMillis DESC, id DESC")
    fun observeNewestFirst(): Flow<List<NetworkMeasurementEntity>>

    @Query("DELETE FROM network_measurement")
    suspend fun deleteAll()

    @Query(
        "DELETE FROM network_measurement WHERE id NOT IN (" +
            "SELECT id FROM network_measurement ORDER BY takenAtMillis DESC, id DESC LIMIT :keepNewest)"
    )
    suspend fun trimToNewest(keepNewest: Int)
}
