<#
.SYNOPSIS
    Generate DOCS_MAP.md and sitemap.xml from the document registry.

.DESCRIPTION
    Exit codes: 0 = generated or current, 1 = generated output drifted in -Check mode, 2 = invalid invocation.
#>
[CmdletBinding()]
param(
    [switch] $Check,
    [string] $RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
)

$ErrorActionPreference = 'Stop'

function Set-GeneratedFile {
    param([string] $Path, [string] $Content)
    $current = if (Test-Path -LiteralPath $Path) { Get-Content -LiteralPath $Path -Raw -Encoding utf8 } else { $null }
    if ($current -eq $Content) { return $false }
    if (-not $Check) { [IO.File]::WriteAllText($Path, $Content, [Text.UTF8Encoding]::new($false)) }
    return $true
}

try {
    $registryPath = Join-Path $RepoRoot 'docs/DOCUMENT_REGISTRY.jsonl'
    $records = @(Get-Content -LiteralPath $registryPath -Encoding utf8 | Where-Object { $_.Trim() } |
        ForEach-Object { $_ | ConvertFrom-Json } | Sort-Object category, title)
    $map = [System.Text.StringBuilder]::new()
    [void]$map.AppendLine('---')
    [void]$map.AppendLine('layout: default')
    [void]$map.AppendLine('title: Project Documentation Map')
    [void]$map.AppendLine('permalink: /docs/DOCS_MAP.html')
    [void]$map.AppendLine('---')
    [void]$map.AppendLine()
    [void]$map.AppendLine('# Project Documentation Map')
    [void]$map.AppendLine()
    [void]$map.AppendLine('Generated from `docs/DOCUMENT_REGISTRY.jsonl`. Do not edit this file by hand.')
    foreach ($group in ($records | Group-Object category)) {
        [void]$map.AppendLine()
        [void]$map.AppendLine(('## {0}' -f $group.Name))
        [void]$map.AppendLine()
        [void]$map.AppendLine('| Document group | Audience | Published | Product areas | Files |')
        [void]$map.AppendLine('|---|---|---|---|---|')
        foreach ($record in ($group.Group | Sort-Object title)) {
            $files = (@($record.paths) -join '<br>') -replace '\|', '\\|'
            $areas = @($record.product_areas) -join ', '
            [void]$map.AppendLine(('| {0} | {1} | {2} | {3} | `{4}` |' -f $record.title, $record.audience, $record.published, $areas, $files))
        }
    }
    $mapContent = $map.ToString()
    $sitemap = [System.Text.StringBuilder]::new()
    [void]$sitemap.AppendLine('<?xml version="1.0" encoding="UTF-8"?>')
    [void]$sitemap.AppendLine('<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">')
    $siteBase = 'https://serzhyale.github.io/FastMediaSorter_mob_v2'
    foreach ($record in ($records | Where-Object { $_.published -and $_.indexable } | Sort-Object url)) {
        $localized = $record.localized_urls
        if (-not $localized) {
            # Single-language record: one entry, no hreflang cluster to describe.
            [void]$sitemap.AppendLine('  <url>')
            [void]$sitemap.AppendLine("    <loc>$siteBase$($record.url)</loc>")
            [void]$sitemap.AppendLine('  </url>')
            continue
        }
        # Translated record: every language is its own indexable page, and each entry repeats the
        # whole cluster including a self-reference - a version listed only as someone else's
        # alternate is routinely left unindexed.
        $langs = @($record.languages | Where-Object { $localized.PSObject.Properties.Name -contains $_ })
        $default = if ($langs -contains 'en') { 'en' } else { $langs[0] }
        foreach ($lang in $langs) {
            [void]$sitemap.AppendLine('  <url>')
            [void]$sitemap.AppendLine("    <loc>$siteBase$($localized.$lang)</loc>")
            foreach ($alt in $langs) {
                [void]$sitemap.AppendLine(('    <xhtml:link rel="alternate" hreflang="{0}" href="{1}{2}"/>' -f $alt, $siteBase, $localized.$alt))
            }
            [void]$sitemap.AppendLine(('    <xhtml:link rel="alternate" hreflang="x-default" href="{0}{1}"/>' -f $siteBase, $localized.$default))
            [void]$sitemap.AppendLine('  </url>')
        }
    }
    [void]$sitemap.AppendLine('</urlset>')
    $mapDrift = Set-GeneratedFile -Path (Join-Path $RepoRoot 'docs/DOCS_MAP.md') -Content $mapContent
    $siteDrift = Set-GeneratedFile -Path (Join-Path $RepoRoot 'sitemap.xml') -Content ($sitemap.ToString())
    if ($Check -and ($mapDrift -or $siteDrift)) { Write-Host 'Generated document views are stale.' -ForegroundColor Red; exit 1 }
    $message = if ($Check) { 'Generated document views are current.' } else { 'Generated document views written.' }
    Write-Host $message -ForegroundColor Green
    exit 0
} catch {
    Write-Error $_.Exception.Message -ErrorAction Continue
    exit 2
}
