<#
.SYNOPSIS
    Test suite for the last-edited stamp: scripts/docs/lib/doc-stamp.ps1 and stamp-doc-dates.ps1.

.DESCRIPTION
    Subject: scripts/docs/lib/doc-stamp.ps1, scripts/docs/stamp-doc-dates.ps1

    Asserts where the stamp lands (after front matter and leading comments in Markdown, after <body>
    in HTML), that stripping it restores the original text byte for byte, that line endings and the
    BOM survive, and - on a scratch tree - that a second run writes nothing, that an edited file is
    restamped from its own mtime, and that a generated file is left alone.

.EXAMPLE
    pwsh -NoProfile -File scripts/docs/stamp-doc-dates.tests/Run-Tests.ps1

.NOTES
    Exit codes:
      0  every assertion passed
      1  at least one assertion failed
      2  could not verify: the library or the script is missing
#>
[CmdletBinding()]
param(
    [string] $RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..\..\..')).Path
)

$ErrorActionPreference = 'Stop'

$lib = Join-Path $RepoRoot 'scripts/docs/lib/doc-stamp.ps1'
$script = Join-Path $RepoRoot 'scripts/docs/stamp-doc-dates.ps1'
foreach ($required in @($lib, $script)) {
    if (-not (Test-Path -LiteralPath $required)) {
        Write-Error "missing: $required" -ErrorAction Continue
        exit 2
    }
}
. $lib

$script:Failures = [System.Collections.Generic.List[string]]::new()

function Assert-That {
    param([Parameter(Mandatory)] [string] $Name, [Parameter(Mandatory)] [bool] $Condition, [string] $Detail)
    if ($Condition) {
        Write-Host "  PASS  $Name"
    } else {
        Write-Host "  FAIL  $Name  $Detail" -ForegroundColor Red
        $script:Failures.Add($Name)
    }
}

$date = '26.10.06 14:32'

# --- Markdown placement
$withFront = "---`nlayout: default`npermalink: /x.html`n---`n<!-- GENERATED by x -->`n# Title`n"
$stamped = Add-DocStamp -Text $withFront -Kind md -Date $date
Assert-That 'md: front matter stays first' ($stamped.StartsWith("---`nlayout: default")) $stamped
Assert-That 'md: stamp follows the leading comment' ($stamped -match '(?s)-->\n<sub class="doc-stamp">26\.10\.06 14:32</sub>\n\n# Title') $stamped
Assert-That 'md: strip restores the original' ((Remove-DocStamp $stamped) -ceq $withFront)

$plain = "# Plain`r`nbody`r`n"
$plainStamped = Add-DocStamp -Text $plain -Kind md -Date $date
Assert-That 'md: CRLF file gets CRLF around the stamp' ($plainStamped.StartsWith("<sub class=`"doc-stamp`">$date</sub>`r`n`r`n# Plain"))
Assert-That 'md: CRLF strip restores the original' ((Remove-DocStamp $plainStamped) -ceq $plain)

$again = Add-DocStamp -Text $plainStamped -Kind md -Date '26.10.07 09:05'
Assert-That 'md: a second stamp replaces the date, never adds a line' ((([regex]::Matches($again, 'doc-stamp')).Count -eq 1) -and $again.Contains('26.10.07 09:05'))

# --- HTML placement
$html = "---`npermalink: /a/`nlayout: null`n---`n<!DOCTYPE html>`n<html><head></head>`n<body class=`"a`">`n<p>x</p>`n</body></html>"
$htmlStamped = Add-DocStamp -Text $html -Kind html -Date $date
Assert-That 'html: stamp is the first thing inside body' ($htmlStamped -match '<body class="a">\n<div class="doc-stamp"[^>]*>26\.10\.06 14:32</div>\n<p>x</p>') $htmlStamped
Assert-That 'html: strip restores the original' ((Remove-DocStamp $htmlStamped) -ceq $html)
Assert-That 'html: a fragment without body has no place for a stamp' ($null -eq (Add-DocStamp -Text '<div>x</div>' -Kind html -Date $date))

# --- on a scratch tree
$tmp = Join-Path ([IO.Path]::GetTempPath()) ("stamp-tests-" + [guid]::NewGuid().ToString('N'))
New-Item -ItemType Directory -Path (Join-Path $tmp 'docs') -Force | Out-Null
try {
    # The script resolves the repo root from its own location, so the scratch tree gets a copy of it.
    New-Item -ItemType Directory -Path (Join-Path $tmp 'scripts/docs/lib') -Force | Out-Null
    Copy-Item $script (Join-Path $tmp 'scripts/docs/stamp-doc-dates.ps1')
    Copy-Item $lib (Join-Path $tmp 'scripts/docs/lib/doc-stamp.ps1')
    $runner = Join-Path $tmp 'scripts/docs/stamp-doc-dates.ps1'

    $bomFile = Join-Path $tmp 'docs/bom.md'
    $genFile = Join-Path $tmp 'docs/gen.md'
    $editFile = Join-Path $tmp 'docs/edit.md'
    [IO.File]::WriteAllText($bomFile, "# Bom`n", [Text.UTF8Encoding]::new($true))
    [IO.File]::WriteAllText($genFile, "<!-- GENERATED by x. Do not edit by hand. -->`n# Gen`n", [Text.UTF8Encoding]::new($false))
    [IO.File]::WriteAllText($editFile, "# Edit`n", [Text.UTF8Encoding]::new($false))
    $old = [datetime]'2026-01-02 03:04:30'
    foreach ($f in @($bomFile, $genFile, $editFile)) { [IO.File]::SetLastWriteTime($f, $old) }

    $null = & pwsh -NoProfile -File $runner -All -Quiet
    $bomBytes = [IO.File]::ReadAllBytes($bomFile)
    Assert-That 'script: BOM survives' ($bomBytes[0] -eq 0xEF -and $bomBytes[1] -eq 0xBB -and $bomBytes[2] -eq 0xBF)
    Assert-That 'script: stamp is the file mtime floored to the minute' ([IO.File]::ReadAllText($editFile).StartsWith('<sub class="doc-stamp">26.01.02 03:04</sub>'))
    Assert-That 'script: mtime is restored after writing' ((Get-Item $editFile).LastWriteTime -eq $old)
    Assert-That 'script: a generated file is left alone' (-not [IO.File]::ReadAllText($genFile).Contains('doc-stamp'))

    $before = (Get-Item $editFile).LastWriteTimeUtc.Ticks
    $null = & pwsh -NoProfile -File $runner -All -Quiet
    Assert-That 'script: a second run changes nothing' ((Get-Item $editFile).LastWriteTimeUtc.Ticks -eq $before)

    $null = & pwsh -NoProfile -File $runner -All -Check -Quiet
    Assert-That 'script: -Check passes on a current tree' ($LASTEXITCODE -eq 0)

    $newer = [datetime]'2026-03-04 05:06:00'
    Add-Content -LiteralPath $editFile -Value 'more'
    [IO.File]::SetLastWriteTime($editFile, $newer)
    $null = & pwsh -NoProfile -File $runner -All -Check -Quiet
    Assert-That 'script: -Check flags an edited file as stale' ($LASTEXITCODE -eq 1)

    $null = & pwsh -NoProfile -File $runner -All -Quiet
    $edited = [IO.File]::ReadAllText($editFile)
    Assert-That 'script: an edited file is restamped from its new mtime' ($edited.StartsWith('<sub class="doc-stamp">26.03.04 05:06</sub>'))
    Assert-That 'script: restamping keeps the body and adds no second stamp' ((([regex]::Matches($edited, 'doc-stamp')).Count -eq 1) -and $edited.Contains('more'))
} finally {
    Remove-Item -LiteralPath $tmp -Recurse -Force -ErrorAction SilentlyContinue
}

if ($script:Failures.Count -gt 0) {
    Write-Host "stamp-doc-dates tests: FAIL ($($script:Failures.Count)): $($script:Failures -join '; ')" -ForegroundColor Red
    exit 1
}
Write-Host 'stamp-doc-dates tests: PASS' -ForegroundColor Green
exit 0
